### PR TITLE
Expose react to extensions

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes "module not found" error in production build. Also makes sense because we really don't want to have multiple different react versions.

### CODE REVIEW

**Review by nevalla — APPROVED** [review]
LGTM

**Comment by ixrock** [comment]
Now we have 2 same bundled versions of `React` in `build/Lens.js` and `build/Lens-extensions-api.js`?
We should provide ability for normal `import React from "react"` for extensions by tweaking webpack externals/alias.

**Comment by jakolehm** [comment]
@ixrock I tried externals but couldn't get it to work.

**Comment by ixrock** [comment]
@jakolehm ok, I'll try to figure out how to overcome this issue a bit later.

**Pull request merged**
