### PR TITLE
Change log level to file always be debug

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Comment by jim-docker** [comment]
Should all `logger.debug()` calls end up in the file? I noticed that [this logging](https://github.com/lensapp/lens/blob/1aabadd60fd6a9b9b1726371c8ffeff262099670/src/main/routes/port-forward/functionality/port-forward.ts#L83) does not appear in the file (unless I start the app in the terminal with `DEBUG=1` - tested on linux)

**Comment by Nokel81** [comment]
@jim-docker Yes that should show up. I found that the file logs show up in `OpenLens` folder (not `OpenLensDev`).

**Comment by jim-docker** [comment]
Hmm, that's where I was looking (I did `make build` and ran the AppImage)

**Comment by Nokel81** [comment]
Are you sure that we were triggering that log line? Because when I do a `make build` and then run it (on macOS) I do see some `debug` lines.

**Comment by jim-docker** [comment]
Yeah, that's what is weird. I saw some debug logging, but that particular port-forward debug logging did not show up in the file till I started the AppImage with DEBUG=1

**Review by jim-docker — APPROVED** [review]

**Pull request merged**
