### PR TITLE
Upgrade ReactSelect to latest version

### PR DESCRIPTION
**Pull request by ixrock**
fix: `prop.styles` was previously ignored before passing to final `react-select` component for rendering
fix: dev-mode error in `@pmmmwh/react-refresh-webpack-plugin`, close #5282

### CODE REVIEW

**Review by Nokel81 — DISMISSED** [review]

**Review by Nokel81 — DISMISSED** [review]

**Review by Nokel81 — DISMISSED** [review]

**Review by panuhorsmalahti — DISMISSED** [review]

**Review by Nokel81 — APPROVED** [review]

**Comment by ixrock** [comment]
@panuhorsmalahti PTALA, all tests fixed.

**Comment by Nokel81** [comment]
@ixrock FYI There might be a conflict with #5282 given that it seems you have also fixed the dev mode in this PR. We probably could just merge both of these since you have already gotten the approval once. WDYT?

**Comment by ixrock** [comment]
> @ixrock FYI There might be a conflict with #5282 given that it seems you have also fixed the dev mode in this PR. We probably could just merge both of these since you have already gotten the approval once. WDYT?

It should be easy to fix or even auto-fixable by Github? Do we still need both?
I assume conflict may be because `@pmmmwh/react-refresh-webpack-plugin`, right?

**Comment by Nokel81** [comment]
> I assume conflict may be because @pmmmwh/react-refresh-webpack-plugin, right?

Yes.

Should be able to be done on github maybe. We need the other one because it includes a CI check to try and catch things like this in the future.

**Review by panuhorsmalahti — APPROVED** [review]

**Pull request merged**
