### PR TITLE
Upgrade to electron 13.5.0

### LINKED ISSUE #3896: Does not open in Ubuntu 21.10
**Describe the bug**
When I open the program it just closes, I tried to open it through the terminal and it shows this error that is in the screenshot.

**To Reproduce**
1. Open Lens

**Expected behavior**
Opening normaly

**Screenshots**
image
image

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (.deb file in Linux):
Ubuntu 21.10

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
 /usr/bin/lens  
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +9ms
info:    ▪ 🚀 Starting Lens from "/opt/Lens/lens" +100ms
info:    ▪ 🐚 Syncing shell environment +0ms
info:    ▪ 💾 Loading stores +208ms
info:    ▪ [BS]: LOADED from /home/luizjr/.config/Lens/lens-user-store.json +26ms
info:    ▪ [DA]: LOADED from /home/luizjr/.config/Lens/lens-cluster-store.json +33ms
info:    ▪ [NU]: LOADED from /home/luizjr/.config/Lens/lens-hotbar-store.json +4ms
info:    ▪ [MT]: LOADED from /home/luizjr/.config/Lens/lens-extensions.json +1ms
info:    ▪ [C]: LOADED from /home/luizjr/.config/Lens/lens-filesystem-provisioner-store.json +1ms
info:    ▪ [KA]: LOADED from /home/luizjr/.config/Lens/lens-weblink-store.json +2ms
info:    ▪ 🔌 Starting LensProxy +11ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:46237 +3ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ ⚡ LensProxy connection OK +123ms
info:    ▪ 🖥️  Starting WindowManager +1ms
APPIMAGE env is not defined, current application is not an AppImage
info:    ▪ 🧩 Initializing extensions +28ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /home/luizjr/.config/Lens +1ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at /home/luizjr/.config/Lens +151ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[51827:0926/022529.445906:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at /home/luizjr/.config/Lens +656ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /home/luizjr/.k8slens/extensions +6ms
Failed to generate minidump.[1]    51827 illegal hardware instruction (core dumped)  /usr/bin/lens

```

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/3896

### CODE REVIEW

**Review by jakolehm — COMMENTED** [review]
`.yarnrc` needs also an update.

**Comment by Nokel81** [comment]
@jakolehm What is the `.yarnrc` for. I couldn't find anything online about the values we have in that file. Except that if you run `yarn config list` you get those values too.

**Review by luizjr — APPROVED** [review]
I saw you updated .yarnrc and changed the Electron version.
It's approved by me, and I'm eagerly awaiting the build to test.

**Comment by jakolehm** [comment]
> @jakolehm What is the `.yarnrc` for. I couldn't find anything online about the values we have in that file. Except that if you run `yarn config list` you get those values too.

Originally `.yarnrc` was configured to allow native node modules to be built against right Electron version. I'm not sure if this is still needed.. anyway if we have that file it should be in-sync with the used Electron version.

**Review by jakolehm — APPROVED** [review]

**Pull request closed without merging**
