### PR TITLE
[BREAKING]: refine and document cluster feature api

### LINKED ISSUE #1506: Refine clusterFeatures api
remove unused fields, some refactoring, add documentation

### PR DESCRIPTION
**Pull request by jim-docker**
cleaned up and documented cluster-feature, and necessary mods to metrics-feature extension in preparation for writing the extension guide documentation

fixes #1506

### CODE REVIEW

**Comment by jakolehm** [comment]
Note: this is a breaking change `config` is now `templateContext`.

**Review by jakolehm — COMMENTED** [review]
LGTM but linter is not happy.

**Comment by jim-docker** [comment]
> Note: this is a breaking change `config` is now `templateContext`.

Have any of our partners implemented a clusterFeature extension? Hopefully this isn't a big deal...

**Comment by jakolehm** [comment]
> > Note: this is a breaking change `config` is now `templateContext`.
> 
> Have any of our partners implemented a clusterFeature extension? Hopefully this isn't a big deal...

I only know about this: https://github.com/aquasecurity/starboard-lens-extension/blob/main/src/starboard-feature.ts

But this change does not seem to affect it?

**Comment by jim-docker** [comment]
> > > Note: this is a breaking change `config` is now `templateContext`.
> > 
> > 
> > Have any of our partners implemented a clusterFeature extension? Hopefully this isn't a big deal...
> 
> I only know about this: https://github.com/aquasecurity/starboard-lens-extension/blob/main/src/starboard-feature.ts
> 
> But this change does not seem to affect it?

I agree, no reference to `config`, everything should work as before

**Review by jakolehm — APPROVED** [review]

**Pull request merged**
