### PR TITLE
Add colour picker for Letter Cluster Icons

### LINKED ISSUE #2379: Option To Select Cluster Icon Color
**What would you like to be added**:
Option to select the cluster icon color

**Why is this needed**:
Just a nice to have. Not really need, but just would help to identify which cluster is which.

### PR DESCRIPTION
**Pull request by Nokel81**
This is my proposal for augmenting #2153.

1. Add changing background colour
2. Remove default of blue background (the white boarder represents active well enough)

### CODE REVIEW

**Comment by jakolehm** [comment]
@Nokel81 could you describe what things are changed and maybe include a screenshot (or video).

**Comment by Nokel81** [comment]
This PR adds the ability to set the icon colour (for when the letters are used). It also changes a bit of the styling around the letters so that it works with all colours.

**Comment by Nokel81** [comment]
https://user-images.githubusercontent.com/8225332/111158857-e6cca480-856e-11eb-99eb-2f953a18a9ba.mov

**Comment by Nokel81** [comment]
I have fixed the sluggishness in the video. And changed how the label is.

Screen Shot 2021-03-15 at 9 55 01 AM

**Comment by Nokel81** [comment]
In the future we could clean up the file picker it self so that the icon could be clicked, but I think that is out of scope.

**Comment by Nokel81** [comment]
Closing because we don't have cluster icons any more and this should be split

**Pull request closed without merging**
