### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
Added License section in Readme.

### CODE REVIEW

**Review by aleksfront — APPROVED** [review]

**Comment by SaptarshiSarkar12** [comment]
@ixrock @jim-docker
Please review this PR.

**Comment by SaptarshiSarkar12** [comment]
Thanks @aleksfront for reviewing this PR.

**Comment by SaptarshiSarkar12** [comment]
@aleksfront please see why this is failing.
Screenshot_2022-09-12-19-36-16

**Review by Iku-turso — APPROVED** [review]

**Comment by SaptarshiSarkar12** [comment]
@Iku-turso @aleksfront please merge this PR.

**Pull request merged**
