### PR TITLE
Change add-cluster to single column layout

### PR DESCRIPTION
**Pull request by jakolehm**
- more unified look&feel (preferences & cluster settings are already single column)
- close button (X)
- longer description/help text moved to docs

image

### CODE REVIEW

**Comment by aleksfront** [comment]
Probably needs some padding fine-tuning between the lines. I will push changes in this branch.

**Comment by jakolehm** [comment]
> Probably needs some padding fine-tuning between the lines. I will push changes in this branch.

I already did some style cleanup, it should be a bit better.

**Comment by aleksfront** [comment]
Here is complete look
add clusters light 1
add clusters light 2
add clusters dark 2
add clusters dark 1

**Comment by jakolehm** [comment]
@aleksfront thanks!

**Review by aleksfront — APPROVED** [review]

**Pull request merged**
