### PR TITLE
Fix RoleBindingDetails not rendering the name of the role binding

### PR DESCRIPTION
**Pull request by Nokel81**
- Move all strings of the form {`...`} to use just ""

- Fix RoleBindingDetails not rendering the name of the role binding

Signed-off-by: Sebastian Malton <sebastian@malton.name>

follow up to #1874

### CODE REVIEW

**Review by jim-docker — APPROVED** [review]

**Comment by nevalla** [comment]
> Move all strings of the form {...} to use just ""

So `{...}` does not work anymore?

> Fix RoleBindingDetails not rendering the name of the role binding

Would be make clearer if this change was in separate PR. Now it's a bit hard to spot that fix.

**Comment by Nokel81** [comment]
@nevalla Using `""` is clearer of intent and is certainly easier to parse for the JS runtime that `{\`\`}`.

As for the other two, I put them in one PR because these were all left over bugs/TODOs from the removal of langci.

**Comment by nevalla** [comment]
Okay...got it now. I was just a bit confused because this PR title says this fixes removal of langci so I initially thought something is broken there. But now I get it that removal of langci PR introduced that bug in RoleBinding details?

**Comment by Nokel81** [comment]
Yes that is correct

**Review by jakolehm — APPROVED** [review]

**Review by nevalla — APPROVED** [review]

**Pull request merged**
