### PR TITLE
Split internal functionality of Cluster to ManagedCluster

### PR DESCRIPTION
**Pull request by jakolehm**
- splits functionality that can only work in main process to a facade class called `ManagedCluster`
- simplifies Cluster api that is exposed via extension-api

Requires #1225

### CODE REVIEW

**Comment by Nokel81** [comment]
This PR will definetly conflict with the work I am doing to solve #1316. Do you want me to push that work to a PR before this gets merged so we can work in parallel?

**Comment by jakolehm** [comment]
> This PR will definetly conflict with the work I am doing to solve #1316. Do you want me to push that work to a PR before this gets merged so we can work in parallel?

You mean #1453 ?

**Comment by Nokel81** [comment]
I do, I had not yet made that PR when I previously wrote.

**Comment by jakolehm** [comment]
Closing because impossible to rebase properly.

**Pull request closed without merging**
