### PR TITLE
Electron 13.4.0

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Review by aleksfront — DISMISSED** [review]
LGTM, works without issues.

**Review by jweak — COMMENTED** [review]
Checked with breaking changes log from Electron. Everything else checks out but I found that we use a deprecated event on window manager.

https://www.electronjs.org/docs/breaking-changes#deprecated-webcontents-new-window-event

https://github.com/lensapp/lens/blob/d448017f334a39b0ee9d974d867e236b4e0104e2/src/main/window-manager.ts#L110-L112

**Comment by jakolehm** [comment]
> Checked with breaking changes log from Electron. Everything else checks out but I found that we use a deprecated event on window manager.
> 
> https://www.electronjs.org/docs/breaking-changes#deprecated-webcontents-new-window-event
> 
> https://github.com/lensapp/lens/blob/d448017f334a39b0ee9d974d867e236b4e0104e2/src/main/window-manager.ts#L110-L112

Good catch!

**Comment by jakolehm** [comment]
@aleksfront @jweak ptal again.

**Review by jweak — APPROVED** [review]
LGTM

**Pull request merged**
