### PR TITLE
Updated regex for isUrl to allow for an empty string

### LINKED ISSUE #992: Cluster settings http_proxy validation issue
**Describe the bug**

image

Validation fails if field is cleared.

### PR DESCRIPTION
**Pull request by stevejr**
Updated regex for isUrl to allow for an empty string aswell as a correct URL.

Fixes #992 

Signed-off-by: Steve Richards <srichards@mirantis.com>

### CODE REVIEW

**Review by nevalla — APPROVED** [review]
LGTM

**Comment by Nokel81** [comment]
Just wondering why we are keeping a regex of what a URL is and not just using the built in URL parser in the JS spec

**Comment by stevejr** [comment]
> Just wondering why we are keeping a regex of what a URL is and not just using the built in URL parser in the JS spec

I wasn't sure how to still allow for an empty field with a built in parser (Was you thinking of the URL builtin or something from validate.js?)

**Comment by Nokel81** [comment]
Well I was thinking something along the lines of:

```javascript
value => {
    try {
        if (value) {
            new Url(value)
        }
        return true
    } catch (err) {
        return false
    }
}
```

**Comment by stevejr** [comment]
But using URL will not parse and validate the contents. for example, I tried a URL with an invalid protocol and it still returned back ok.

**Comment by Nokel81** [comment]
Ah I see, then either we can validate the protocol is one that we want or just keep the regex.

**Pull request merged**
