### PR TITLE
Add auto-detect support for Victoria Metrics Single

### PR DESCRIPTION
**Pull request by jakolehm**
Adds auto-detect support for Victoria Metrics Single version.

### CODE REVIEW

**Review by stevejr — APPROVED** [review]
LGTM

If the user changes the Chart name by setting `values.nameOverride` then this will fail but at least that is known.

**Review by nevalla — APPROVED** [review]
LGTM

**Review by jim-docker — COMMENTED** [review]
I can't get Lens to use vm. I followed [these instructions](https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-single.html?highlight=helm#1-victoriametrics-helm-repository), verified with grafana. The labels/selectors are correct for `getFirstNamespacedService()`. What am I missing? The Prometheus service address on the cluster settings page is not relevant, right? Or the name is inaccurate now. Setting it explicitly (to `default/vmsingle-victoria-metrics-single-server:8428`) didn't help anyway. Also tried using the name same as the chart (`victoria-metrics-single`).

**Comment by jakolehm** [comment]
> I can't get Lens to use vm.

@jim-docker my cluster seems to have a custom config, will investigate this more when I have a bit of time.

**Pull request merged**
