### PR TITLE
fix jsonnet error with kube-prometheus >= v0.8

### PR DESCRIPTION
**Pull request by elvischan-crypto**
kubelet ServiceMonitor moved to kubernetesControlPlane starting from v0.8

### CODE REVIEW

**Comment by Nokel81** [comment]
Thanks for the PR, given that some people might still be running 0.8, I think that this should probably be a switch or maybe dependent on the version.

**Comment by elvischan-crypto** [comment]
sure, and my bad that it should be >= 0.8.

Also, with the cloud provide phasing out the k8s 1.19 such as eks 1.19 EOS end of this month, I think more and more people would need to update >= 0.8

**Comment by Nokel81** [comment]
Oh I have no doubt that more people will be using the newer versions. We tend to try and support more than that though.

**Comment by Nokel81** [comment]
@elvischan-crypto To get this PR merged, I think all that would be needed is adding a note in `troubleshooting/custom-prometheus.md` that says that the file is for >= v0.8

**Review by Nokel81 — APPROVED** [review]

**Comment by elvischan-crypto** [comment]
sorry for late reply, thanks for updating the docs

**Pull request merged**
