### PR TITLE
Use configured NPM registry by default

### LINKED ISSUE #3374: Changing npm registry for installing extentions
Lens ver: 5.0.2-latests.20210705.2

I find out that's current registry for installing all extentions is hardcoded:

> export async function attemptInstallByInfo({ name, version, requireConfirmation = false }: ExtensionInfo) {
>   const disposer = ExtensionInstallationStateStore.startPreInstall();
>   const registryUrl = new URLParse("https://registry.npmjs.com").set("pathname", name).toString();

```
{url: "https://registry.npmjs.com/@nevalla/kube-resource-map", err: Error: Client network socket disconnected before secure TLS connection was established
    at connR…}err: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:312:28)
    at TLSSocket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)url: "https://registry.npmjs.com/@nevalla/kube-resource-map"__proto__: Object
Promise.catch (async)
attemptInstallByInfo @ extensions.tsx:304
extensions_installFromInput @ extensions.tsx:452
installFromInput @ extensions.tsx:524
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
```

And because of this I can't use this behind a firewall
I want that lens uses my ~/.npmrc configuration file with my local registry

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/3374

One of the new notifications (for instance if you run `npm config set registry https://google.ca`

Screen Shot 2021-07-15 at 5 41 17 PM

### CODE REVIEW

**Review by jakolehm — COMMENTED** [review]
Does this open new issues when user has configured `.npmrc` for other purposes (not related to Lens)?

**Comment by Nokel81** [comment]
@jakolehm Maybe for other things, but the registry option seems to be only for situations where a corp has a private registry for private packages (and then passes on to the npm registry for everything else) or for firewall issues (like the linked issue).

Would you prefer a user preference instead?

**Review by panuhorsmalahti — DISMISSED** [review]

**Comment by Nokel81** [comment]
@jakolehm Is your question considered a blocking for this PR?

**Comment by Nokel81** [comment]
From discussion:

- This might be surprising for some users. A more safe method of configuration would be to allow users to specify this URL in Lens and/or have a checkbox for using the npmrc configuration.

**Comment by Nokel81** [comment]
@aleksfront I know that this is not super high priority, but this is as far as I was able to get. I don't think it looks very good.

https://user-images.githubusercontent.com/8225332/128079074-534c2fa4-842b-4268-985d-49336306f2de.mov

**Comment by Nokel81** [comment]
Closing this and will open a new PR with a better fix.

**Pull request closed without merging**
