### PR TITLE
Fix prometheus operator support

### LINKED ISSUE #180: Documentation is incorrect for Prometheus troubleshooting
**Describe the bug**
While configuring custom Prometheus according to troubleshooting guide, I was confused which setting should I change in Prometheus configuration

**To Reproduce**
1. Look at README file here: https://github.com/lensapp/lens/blob/936cbd53d400e8973a763373f05514f894a2578a/troubleshooting/custom-prometheus.md

**Expected behavior**
The description should be clear without confusion

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: any
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

### LINKED ISSUE #2503: Cant show metrics with Prometheus Operator
**Describe the bug**
Can't see any metrics from cluster

**To Reproduce**
1. Go to 'Workloads/Pods'
2. Click on 'any pod'
3. See error

**Expected behavior**
That's show the pod's metrics

**Screenshots**
image
image
image
image
image

**Environment (please complete the following information):**
- Lens Version: 4.2.1
- OS: GNU/Linux Manjaro
- Installation method (e.g. snap or AppImage in Linux): Arch AUR that's use the AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```json
{
  "error": {
    "name": "StatusCodeError",
    "statusCode": 400,
    "message": "400 - {\"status\":\"error\",\"errorType\":\"bad_data\",\"error\":\"invalid parameter 'start': cannot parse \\\"\\\" to a valid timestamp\"}",
    "error": {
      "status": "error",
      "errorType": "bad_data",
      "error": "invalid parameter 'start': cannot parse \"\" to a valid timestamp"
    },
    "options": {
      "timeout": 0,
      "resolveWithFullResponse": false,
      "json": true,
      "qs": {
        "query": "sum(kube_node_status_capacity{node=~\"k8s-1|k8s-2|k8s-3|k8s-4\", resource=\"pods\"})",
        "start": "1618082700",
        "end": "1618086300",
        "step": "60",
        "kubernetes_namespace": ""
      },
      "headers": {
        "Host": "3537383f-37ba-4706-adc4-b6acbd7d4d03.localhost:40663"
      },
      "uri": "http://localhost:40663/api-kube/api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/api/v1/query_range",
      "simple": true,
      "transform2xxOnly": false
    },
    "response": {
      "statusCode": 400,
      "body": {
        "status": "error",
        "errorType": "bad_data",
        "error": "invalid parameter 'start': cannot parse \"\" to a valid timestamp"
      },
      "headers": {
        "access-control-allow-origin": "*",
        "content-type": "application/json",
        "date": "Sat, 10 Apr 2021 20:25:58 GMT",
        "server": "nginx/1.18.0",
        "content-length": "117",
        "connection": "close"
      },
      "request": {
        "uri": {
          "protocol": "http:",
          "slashes": true,
          "auth": null,
          "host": "localhost:40663",
          "port": "40663",
          "hostname": "localhost",
          "hash": null,
          "search": "?query=sum%28kube_node_status_capacity%7Bnode%3D~%22k8s-1%7Ck8s-2%7Ck8s-3%7Ck8s-4%22%2C%20resource%3D%22pods%22%7D%29&start=1618082700&end=1618086300&step=60&kubernetes_namespace=",
          "query": "query=sum%28kube_node_status_capacity%7Bnode%3D~%22k8s-1%7Ck8s-2%7Ck8s-3%7Ck8s-4%22%2C%20resource%3D%22pods%22%7D%29&start=1618082700&end=1618086300&step=60&kubernetes_namespace=",
          "pathname": "/api-kube/api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/api/v1/query_range",
          "path": "/api-kube/api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/api/v1/query_range?query=sum%28kube_node_status_capacity%7Bnode%3D~%22k8s-1%7Ck8s-2%7Ck8s-3%7Ck8s-4%22%2C%20resource%3D%22pods%22%7D%29&start=1618082700&end=1618086300&step=60&kubernetes_namespace=",
          "href": "http://localhost:40663/api-kube/api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/api/v1/query_range?query=sum%28kube_node_status_capacity%7Bnode%3D~%22k8s-1%7Ck8s-2%7Ck8s-3%7Ck8s-4%22%2C%20resource%3D%22pods%22%7D%29&start=1618082700&end=1618086300&step=60&kubernetes_namespace="
        },
        "method": "GET",
        "headers": {
          "Host": "3537383f-37ba-4706-adc4-b6acbd7d4d03.localhost:40663",
          "accept": "application/json"
        }
      }
    }
  }
}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
Not needed
```

**Additional context**
I think that is a prometheus api compatibility problem because the error is that lens query with a timestamp not recognized by prometheus service.

### LINKED ISSUE #3263: Lens not able to detect Prometheus installed as Prometheus operator in namespace monitoring
**Describe the bug**
Lens not able to detect Prometheus installed as Prometheus operator in namespace monitoring
(or whatever other setup, monitoring is never visible)

**To Reproduce**
1. Go to 'Settings'
2. Select Prometheus Operator

**Expected behavior**
Monitoring metrics are visible.

**Screenshots**
image

image

image

**Environment (please complete the following information):**
- Lens Version: 5
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Windows setup

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
...
```

### LINKED ISSUE #3917: Lens metrics not working after upgrade to 5.1.3
**Describe the bug**
We recently made the upgrade of lens from 4.2.5 to Lens 5.1.3.
Before the upgrade we were able to view metrics from our cluster in lens. After the upgrade we get "Metrics not available at the moment".

We have Prometheus installed via helm chart in the prometheus namespace, as such we have set the metrics configuration as follows:

Prometheus: Helm
Prometheus Service Address: prometheus/prometheus-server:80

Now the strange part is, using our admin user (full access) we are able to retrieve the metrics. With a user login we are not able to receive the metrics. Our users have restricted access, but were granted the following permissions for the prometheus namespace

Resources: services, services/proxy
Verbs: get, list, watch
Api Groups: ''

I just verified after reinstalling Lens 4.2.5 this still works, but not with the Lens 5.1.3 version.

**To Reproduce**
1. Restrict access to prometheus namespace as seen above
2. Assign the ClusterRole via Rolebinding to current user
3. Set Metrics to Helm with corresponding address
4. Install Lens 5.1.3 -> Missing Metrics
5. Install Lens 4.2.5 -> Metrics available

**Expected behavior**
The Metrics should be available the same as it was in 4.2.5

**Environment (please complete the following information):**
- Lens Version: 5.1.3
- OS: Win10

### PR DESCRIPTION
**Pull request by marcbachmann**
Not sure why this didn't come up already, but all the group_left queries returned an empty result set because the group_left function was used wrong.

What do you think about the changes? Did i miss something?

### CODE REVIEW

**Comment by Nokel81** [comment]
@marcbachmann please sign your commit

**Comment by marcbachmann** [comment]
any updates on this one?

**Comment by Nokel81** [comment]
@nevalla Can you review this?

**Comment by marcbachmann** [comment]
I just verified this again. Without the changes here, the prometheus operator integration is not working.

Left is the query before the fix, to the right the query with the fix:
image

But some queries are still wrong on the Cluster & Node page. Could use an update.

**Review by Nokel81 — DISMISSED** [review]

**Comment by marcbachmann** [comment]
Some additional change we could apply.
Remove the whole group_left support. But i'm not sure what the intention was behind it.
```diff
diff --git a/src/main/prometheus/operator.ts b/src/main/prometheus/operator.ts
index 2f3da4d369..19926f5d00 100644
--- a/src/main/prometheus/operator.ts
+++ b/src/main/prometheus/operator.ts
@@ -38,7 +38,7 @@ export class PrometheusOperator extends PrometheusProvider {
       case "cluster":
         switch (queryName) {
           case "memoryUsage":
-            return `sum(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes))`.replace(/_bytes/g, `_bytes * on (node) group_left(pod,namespace) kube_pod_info{node=~"${opts.nodes}"}`);
+            return `sum(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes))`.replace(/_bytes/g, `_bytes{node=~"${opts.nodes}"}`);
           case "workloadMemoryUsage":
             return `sum(container_memory_working_set_bytes{container!="POD",container!="",instance=~"${opts.nodes}"}) by (component)`;
           case "memoryRequests":
@@ -50,7 +50,7 @@ export class PrometheusOperator extends PrometheusProvider {
           case "memoryAllocatableCapacity":
             return `sum(kube_node_status_allocatable{node=~"${opts.nodes}", resource="memory"})`;
           case "cpuUsage":
-            return `sum(rate(node_cpu_seconds_total{mode=~"user|system"}[${this.rateAccuracy}])* on (node) group_left(pod,namespace) kube_pod_info{node=~"${opts.nodes}"})`;
+            return `sum(rate(node_cpu_seconds_total{node=~"${opts.nodes}", mode=~"user|system"}[${this.rateAccuracy}]))`;
           case "cpuRequests":
             return `sum(kube_pod_container_resource_requests{node=~"${opts.nodes}", resource="cpu"})`;
           case "cpuLimits":
@@ -66,15 +66,15 @@ export class PrometheusOperator extends PrometheusProvider {
           case "podAllocatableCapacity":
             return `sum(kube_node_status_allocatable{node=~"${opts.nodes}", resource="pods"})`;
           case "fsSize":
-            return `sum(node_filesystem_size_bytes{mountpoint="/"} * on (node) group_left(pod,namespace) kube_pod_info{node=~"${opts.nodes}"})`;
+            return `sum(node_filesystem_size_bytes{node=~"${opts.nodes}", mountpoint="/"}) by (node)`;
           case "fsUsage":
-            return `sum(node_filesystem_size_bytes{mountpoint="/"} * on (node) group_left(pod,namespace) kube_pod_info{node=~"${opts.nodes}"} - node_filesystem_avail_bytes{mountpoint="/"} * on (node) group_left(pod,namespace) kube_pod_info{node=~"${opts.nodes}"})`;
+            return `sum(node_filesystem_size_bytes{node=~"${opts.nodes}", mountpoint="/"} - node_filesystem_avail_bytes{node=~"${opts.nodes}", mountpoint="/"}) by (node)`;
         }
         break;
       case "nodes":
         switch (queryName) {
           case "memoryUsage":
-            return `sum((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) * on (node) group_left(pod,namespace) kube_pod_info) by (node)`;
+            return `sum (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) by (node)`;
           case "workloadMemoryUsage":
             return `sum(container_memory_working_set_bytes{container!="POD",container!=""}) by (node)`;
           case "memoryCapacity":
@@ -82,15 +82,15 @@ export class PrometheusOperator extends PrometheusProvider {
           case "memoryAllocatableCapacity":
             return `sum(kube_node_status_allocatable{resource="memory"}) by (node)`;
           case "cpuUsage":
-            return `sum(rate(node_cpu_seconds_total{mode=~"user|system"}[${this.rateAccuracy}]) * on (node) group_left(pod,namespace) kube_pod_info) by (node)`;
+            return `sum(rate(node_cpu_seconds_total{mode=~"user|system"}[${this.rateAccuracy}])) by(node)`;
           case "cpuCapacity":
             return `sum(kube_node_status_allocatable{resource="cpu"}) by (node)`;
           case "cpuAllocatableCapacity":
             return `sum(kube_node_status_allocatable{resource="cpu"}) by (node)`;
           case "fsSize":
-            return `sum(node_filesystem_size_bytes{mountpoint="/"} * on (node) group_left(pod,namespace) kube_pod_info) by (node)`;
+            return `sum(node_filesystem_size_bytes{mountpoint="/"}) by (node)`;
           case "fsUsage":
-            return `sum((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) * on (node) group_left(pod,namespace) kube_pod_info) by (node)`;
+            return `sum(node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) by (node)`;
         }
         break;
       case "pods":
```

**Comment by Nokel81** [comment]
@marcbachmann fair enough, those aren't there in the Lens queries either. Let me see if I can verify that this won't break anyone

**Comment by Nokel81** [comment]
@marcbachmann That worked even better! With the default install of https://github.com/prometheus-operator/kube-prometheus/releases/tag/v0.8.0 and your second change I actually see metrics. Though not for the cluster scoped metrics....

**Comment by marcbachmann** [comment]
> Though not for the cluster scoped metrics....

For the cluster scoped metrics, you'll need `node` labels on `node_memory_MemTotal_bytes`.
Could you check what's on there by default?

I'm using such a config for prometheus/victoriametrics:
```
  relabelConfigs:
    - sourceLabels: [__meta_kubernetes_node_name]
      regex: (.+)
      targetLabel: node
```


But let's go into the direction of bringing lens & prometheus operator closer together. I'll update the PR with the queries above.

**Comment by Nokel81** [comment]
@marcbachmann I don't know how to check that but yes please make those changes this is already an improvement.

**Comment by marcbachmann** [comment]
I'll quickly set it up myself in that case 😃 
you'd need to query prometheus

**Comment by marcbachmann** [comment]
```bash
kubectl create ns prometheus-operator-test
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install -n prometheus-operator-test prometheus prometheus-community/kube-prometheus-stack

kubectl port-forward -n prometheus-operator-test service/prometheus-kube-prometheus-prometheus 9090:9090
> Forwarding from 127.0.0.1:9090 -> 9090
> Forwarding from [::1]:9090 -> 9090
```

image

Looks like there's no normalized node label by default.

But there's `node` on the containers:
```sql
container_cpu_cfs_periods_total{container="backport", endpoint="https-metrics", id="/kubepods/burstable/pod297547c0-88a4-4675-87d9-a752553fed84/ea3df3871a185c29ace47dac15d965d92d0d55296f63572888470c3a6bf0ce22", image="docker.io/livingdocs/drone:v2.2.0", instance="10.135.103.6:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="ea3df3871a185c29ace47dac15d965d92d0d55296f63572888470c3a6bf0ce22", namespace="drone", node="kubernetes-t1p8", pod="drone-68c5c8875b-q8f4m", service="prometheus-kube-prometheus-kubelet"}
````


edit:
Those configs are needed with the example setup above:
```diff
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-kube-prometheus-node-exporter
  namespace: prometheus-operator-test
spec:
  endpoints:
    - port: metrics
+     relabelings:
+       - regex: (.+)
+         sourceLabels:
+           - __meta_kubernetes_endpoint_node_name
+         targetLabel: node
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - prometheus-operator-test
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: prometheus

```

**Comment by marcbachmann** [comment]
I've pushed the changes. And fixed the PVC metrics:
image

### Prometheus Setup

#### [prometheus-community/kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)
```bash
kubectl create ns monitoring
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install -n monitoring prometheus prometheus-community/kube-prometheus-stack -f values.yaml
```

```yaml
# values.yaml
nodeExporter:
  serviceMonitor:
    relabelings:
      - regex: (.+)
        sourceLabels:
          - __meta_kubernetes_endpoint_node_name
        targetLabel: node
```

<details>
  <summary>Or declare a `ServiceMonitor` manually</summary>
  
  ```diff
  apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: prometheus-kube-prometheus-node-exporter
    namespace: monitoring
  spec:
    endpoints:
      - port: metrics
  +     relabelings:
  +       - regex: (.+)
  +         sourceLabels:
  +           - __meta_kubernetes_endpoint_node_name
  +         targetLabel: node
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
        - prometheus-operator-test
    selector:
      matchLabels:
        app: prometheus-node-exporter
        release: prometheus
  ````
</details>

####  [bitnami/kube-prometheus](https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus)

Apply the following configs in your [helm chart config](https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/values.yaml#L1528):
```diff
node-exporter:
  service:
    labels:
      jobLabel: node-exporter
  serviceMonitor:
    enabled: true
    jobLabel: jobLabel
+   relabelings:
+     - regex: (.+)
+        sourceLabels:
+          - __meta_kubernetes_endpoint_node_name
+        targetLabel: node
```

### Lens Setup
image

**Review by Nokel81 — APPROVED** [review]
LGTM! Thanks so much for this work it fixes a lot of issues. Great job!

Does the defaults all work or do users still need to specify that node label? We probably should have some better visibility into which Prometheus labels we use...

**Comment by z0rc** [comment]
Is there a strong requirement to perform relabeling? If queries already tailored to specific prom installation method, maybe labels can be used in a way where relabeling won't be needed.

**Comment by Nokel81** [comment]
@z0rc Are you saying that you currently are using the setting "Prometheus Operator" in Lens and see metrics? Because when I tried it I was getting invalid query errors.

**Comment by z0rc** [comment]
@Nokel81 currently I have prom installed with `kube-prometheus-stack` chart and use "Helm" prom configuration in Lens. This gives me at least pod CPU and memory metrics in prom.

Anyway my question is about relabeling. As I already have prom queries in other services that use default node labels, relabeling will break those queries. So I need to compromise between labels required for Lens and other services.

**Comment by Nokel81** [comment]
@z0rc This PR doesn't affect you since you are using the code under `src/main/prometheus/helm.ts` and this PR affects `src/main/prometheus/operator.ts`.

I agree that being able to customize what labels we use for the queries would be a good thing for the future.

**Comment by z0rc** [comment]
@Nokel81 it affects me in way that I want better metrics in Lens. This PR fixes my use case, see https://github.com/lensapp/lens/issues/3263#issuecomment-933933113. Only relabeling remains.

**Comment by Nokel81** [comment]
@z0rc Now I understand, since you are currently using the helm configuration in Lens you use the `kubernetes_node` label. However, this PR uses the `node` label instead. I think having that label be customizable would be good but I don't think we should block this PR for that.

**Comment by Nokel81** [comment]
@z0rc I have made https://github.com/lensapp/lens/issues/3955, does that sound like what you are talking about?

**Comment by marcbachmann** [comment]
> Is there a strong requirement to perform relabeling? If queries already tailored to specific prom installation method, maybe labels can be used in a way where relabeling won't be needed.

The node label on the node exporter is the only thing to customize as there's no label.
All the other metrics already contain the `node` label, so I think this is fine to define as requirement for now. At least until it's customizable with a config.

**Comment by Nokel81** [comment]
I think maybe we could show that requirement someplace but thanks for the work!

**Comment by marcbachmann** [comment]
We should update the documentation here.
https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md#kube-prometheus

Probably best to take the whole `helm install` command from here https://github.com/lensapp/lens/pull/3653#issuecomment-933921269

And move that into the docs directory.

**Comment by marcbachmann** [comment]
Regarding the missing `container_fs_usage_bytes` metric, that's coming soon in cadvisor.
A PR got merged: https://github.com/google/cadvisor/pull/2936

**Comment by Nokel81** [comment]
Ah so people will just have to upgrade their version.

**Comment by marcbachmann** [comment]
> Ah so people will just have to upgrade their version.

It only got merged into another working branch. Takes some time more. But it will get fixed... somewhen 😁

**Pull request merged**
