### PR TITLE
Fix errors in CI about documentation

### LINKED ISSUE #7581: Generating API docs are failing
https://github.com/lensapp/lens/actions/runs/4742950358/jobs/8421861578

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Review by gabriel-mirantis — APPROVED** [review]

**Comment by jim-docker** [comment]
Trying to test, running `npm run mkdocs:verify` or `npm run mkdocs:serve-local` both lead to

```
Error: Config file 'mkdocs.yml' does not exist.
```

**Comment by Nokel81** [comment]
How do you have `docker` set up? I didn't get it to work using the docker CLI feature in Lens Desktop, I needed to install `mkdocs` locally

**Comment by jim-docker** [comment]
I'm using the docker daemon from minikube

**Comment by Nokel81** [comment]
Following https://apple.stackexchange.com/a/439938 worked for me just now. Might be a configuration issue

**Pull request merged**
