### PR TITLE
add version display to extensions

### LINKED ISSUE #1597: Show extension version in extensions list

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #1597

### CODE REVIEW

**Review by panuhorsmalahti — DISMISSED** [review]

**Review by aleksfront — DISMISSED** [review]
LGTM! But nice to have a screenshot for any of visual fixes.

**Comment by Nokel81** [comment]
> LGTM! But nice to have a screenshot for any of visual fixes.

Oh sorry, I forgot. will next time.

**Comment by jakolehm** [comment]
@Nokel81 screenshot would be nice.

**Comment by Nokel81** [comment]
Screen Shot 2020-12-10 at 12 32 33 PM

Sure @jakolehm. Here is what they currently look like

**Review by panuhorsmalahti — APPROVED** [review]

**Review by aleksfront — APPROVED** [review]

**Pull request merged**
