### PR TITLE
Fix getReleases returning inconsistent data types

### LINKED ISSUE #2346: Unable to interact with deploy chart release
**Describe the bug**
Cannot interact with [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) release in helm. When I select the release, the details page hangs forever. 

I think this is an issue with Lens because I can interact with the release using the `helm` commandline tool i.e. retrieve values, upgrade, etc.

**To Reproduce**
1. deploy release
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack
```
2. once deployed, navigate to Apps > Releases in Lens and select the release.
3. Then the Release details side pane with load forever.

**Expected behavior**
I expect to be able to interact with the release just like I can using the `helm` command line tool.

**Screenshots**
Screen Shot 2021-03-16 at 12 33 37 PM

Here we can see that I can upgrade the release from the command line just fine (ruling out the chart from the problem).

Screen Shot 2021-03-16 at 12 43 00 PM

**Environment (please complete the following information):**
- Lens Version:
```
Lens: 4.1.4
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
Copyright 2020 Mirantis, Inc.
```
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Homebrew

**Kubeconfig:**
The kubeconfig is good because I can interact with other releases in the same cluster. I just can't interact with the kube-prometheus-stack release.

### LINKED ISSUE #2922: Infinite spinner on kube-prometheus helm release details page
**To Reproduce**
- Install kube-prometheus from bitnami helm repo and go to releases/details for it.

master branch, mac

Screen Shot 2021-05-31 at 1 15 54 PM

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/2922

Please ignore all the whitespace changes, they are related to our lint rules (I think). I can revert them if people want.

### CODE REVIEW

**Review by nevalla — APPROVED** [review]
LGTM.

**Comment by Nokel81** [comment]
FYI I figured out why my editor was making so many formatting changes. I thought I had just configured it to run `eslint` on save, but I had also configured it to run "format on save" which I have turned off.

**Review by jim-docker — APPROVED** [review]
So the page now loads but there is still an error (no resources are shown). Another issue?

**Comment by Nokel81** [comment]
> So the page now loads but there is still an error (no resources are shown). Another issue?

No resources are shown if this line throws an error:

https://github.com/lensapp/lens/pull/2924/files#diff-6fa2db2bca3e4b248130c2218e1faca17a9431dfaa0efed6c264d46a62508ab9R174

I looked at those errors during the work on this issue and saw that it was mostly about the namespaces not being "up" yet. I guess we could pass that error on the user somehow.

**Comment by Nokel81** [comment]
Opened https://github.com/lensapp/lens/issues/2937

**Pull request merged**
