### PR TITLE
Add stateful set scale slider

### LINKED ISSUE #389: statefulset scale slider
Deployment has this fancy scale slider, but StatefulSet doesn't have it.

### PR DESCRIPTION
**Pull request by vshakirova**
Hi guys, I've tried to implement a feature according to this issue https://github.com/lensapp/lens/issues/389. Now stateful set has scale dialog and scale slider. 
Please let me know your opinion. 
Screen Shot 2020-11-17 at 10 03 27 AM

Fixes https://github.com/lensapp/lens/issues/389

### CODE REVIEW

**Comment by chenhunghan** [comment]
@vshakirova thanks, the PR looks clean. Could you please write some tests for `statefulset-scale-dialog` React component? For example if user changes the value of `<Slider />`(), is `desiredReplicas ` change accordingly? There is a PR with very similar test cases, for reference:  https://github.com/lensapp/lens/pull/1191

**Comment by vshakirova** [comment]
> @vshakirova thanks, the PR looks clean. Could you please write some tests for `statefulset-scale-dialog` React component? For example if user changes the value of `<Slider />`(), is `desiredReplicas ` change accordingly? There is a PR with very similar test cases, for reference: #1191

thank you for the comment, I'll add tests. :) 
Also, I have one concern. I've taken a look at deployment scale realization and saw that there is a limitation(count of desired replicas must be greater than 0).
I checked that we can scale `statefulset` to 0 using `kubectl`. Do we need that limitation for scale?

**Comment by chenhunghan** [comment]
> Also, I have one concern. I've taken a look at deployment scale realization and saw that there is a limitation(count of desired replicas must be greater than 0).
> 
> I checked that we can scale `statefulset` to 0 using `kubectl`. Do we need that limitation for scale?

Thanks for your question.

Unfortunately I have limited knowledge of stateful set. But I think if it's possible to use kubrctl to scale to zero we should follow kubectl, so there is no limit greater than zero needed.

**Comment by vshakirova** [comment]
Thank you @chenhunghan. I've added some tests and additional checks for `Slider`.  I've spent a lot of time trying to figure out how to check `value` from `Slider` component and did my best. Please let me know if you could suggest a better approach

**Review by chenhunghan — APPROVED** [review]
LGTM, thank you @vshakirova

**Comment by aleksfront** [comment]
Thanks, @vshakirova! Just one more tiny thing. Can you swap plus minus buttons? Just to be consistent with what we have in deployment scale dialog.

Deployment buttons
scale deployment

StatefulSet buttons
scale statefulset

**Review by aleksfront — APPROVED** [review]

**Comment by aleksfront** [comment]
@vshakirova Please chek for lint errors. Tests are failing because of
```
/home/vsts/work/1/s/src/renderer/api/endpoints/stateful-set.api.ts
  23:11  error  Expected property shorthand  object-shorthand
```
You can fix the issue manually or try run `yarn lint:fix`.

**Comment by vshakirova** [comment]
> @vshakirova Please chek for lint errors. Tests are failing because of
> 
> ```
> /home/vsts/work/1/s/src/renderer/api/endpoints/stateful-set.api.ts
>   23:11  error  Expected property shorthand  object-shorthand
> ```
> 
> You can fix the issue manually or try run `yarn lint:fix`.

Thank you, @aleksfront . I've missed new lint rules... I've swapped buttons and fixed lint. But unfortunately, some tests failed because of timeout (only on Linux)
`This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.`
Could you tell me please how can I rerun checks?
Screen Shot 2020-11-25 at 1 28 40 PM

**Comment by aleksfront** [comment]
@vshakirova Tests are green now, so nothing blocks to merge.

**Pull request merged**
