### PR TITLE
Fix: logs data disapearing causing crashes

### PR DESCRIPTION
**Pull request by Nokel81**
I guess that it would better to figure out why the `DockTabStore` is loosing information. Any ideas @ixrock ? Could it be that the OS is deleting a cache file?

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes: #2458

### CODE REVIEW

**Comment by jim-docker** [comment]
Is @aleksfront also working on a fix for this?

**Comment by Nokel81** [comment]
@jim-docker I don't know, I told him about this PR but he didn't respond.

**Review by aleksfront — APPROVED** [review]
LGTM

**Review by jim-docker — APPROVED** [review]
LGTM. Couldn't reproduce the error before (or after) this fix

**Pull request merged**
