### PR TITLE
Fix node-fetch load on renderer

### LINKED ISSUE #3777: High CPU usage on 5.2
**Describe the bug**
After upgrade to recent version lens started to use cpu very intense. It takes about one full core and quickly makes fan loud. I can't see that cpu usage is even higher when I'm connected to some cluster and running some consoles there. It's about 40% of cpu. When it's completely idle (disconnected from everything on welcome screen) it's about 20%.

**To Reproduce**
Nothing special - just running lens on windows 10. 

**Expected behavior**
It should not eat so much CPU for sure. 

**Screenshots**
This is when it's completely idle on start screen: 
image

When it's connected and used normally it's much worse: 
image

**Environment (please complete the following information):**
- Lens Version: latest - 5.2 
- Windows 10 
- Installed via installer from homepage

**Additional context**
This happened soon after update, I see it's using GPU but same thing happens in chrome where hardware accelleration is disabled. I don't know how to open "chrome://gpu" panel information, but this may be good point to start. 

Please take a look at performane console with lens running and closed (last few seconds) 
image

### LINKED ISSUE #3796: Blue screen of death when trying to connect
**Describe the bug**
When trying to connect using lens 5.2 Windows crashes to BSOD mode with kernel mode heap corruption.

**To Reproduce**
1. Go to a cluster and connect
2. Wait for crash

**Expected behavior**
No BSOD.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2 - downloaded it today
- OS: [e.g. OSX] windiws 10
- Installation method (e.g. snap or AppImage in Linux): exe file

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
This config works well with version 4.2.5
```
your kubeconfig here
```

**Additional context**
Upgraded from 4.2.5 since I had connection problems in 5.1 version. Hoped they will be solved in 5.2 version and they were, but I still can't use latest version...
Related to: #3226

### LINKED ISSUE #3831: Type Error: Only absolute URLs are supported
image
After upgrading to 5.2X, the api call failed with above errors. it works fine before 5.2X.

macOS: macOS Big Sur version 11.6
mackbook Pro 16-inch, 2019

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #3831 

Might fix #3796
Might fix #3777

### CODE REVIEW

**Comment by jakolehm** [comment]
Renderer cpu usage on Windows 10 when connected to a cluster (Workloads -> pods) 
image

**Comment by jakolehm** [comment]
With 2k pods:
image

**Review by nevalla — APPROVED** [review]

**Comment by jakolehm** [comment]
I still see high cpu from time to time if I disconnect/reconnect multiple times a cluster.. so this is not a complete fix for the performance issue.

**Comment by DougTrajano** [comment]
Issue #3796 was not fixed with this merge. :/

**Pull request merged**
