### PR TITLE
Fixing tray icon color on macOS Big Sur

### LINKED ISSUE #1388: Incorrect tray icon in Light theme macOS Big Sur
**Describe the bug**
image

_Light theme:_ (incorrect)
image

_Dark theme:_ (all good)
image

### PR DESCRIPTION
**Pull request by aleksfront**
Using [Template Image](https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image) technique to set tray icon. MacOS automatically changes its color if filename ends with `Template`.

Windows
windows tray icon

macOS Catalina
catalina tray icon

macOS Big Sur
big sur tray icon

Fixes #1388

### CODE REVIEW

**Review by Nokel81 — APPROVED** [review]
Looks good, though on bigSur it doesn't seem to be changing colours (in your gif)

**Comment by aleksfront** [comment]
> Looks good, though on bigSur it doesn't seem to be changing colours (in your gif)

Yep, I suggest all colors will be white regardless of selected theme.

**Comment by Nokel81** [comment]
> > Looks good, though on bigSur it doesn't seem to be changing colours (in your gif)
> 
> Yep, I suggest all colors will be white regardless of selected theme.

Why do we want that? That seems like the opposite of how it works on Catalina

**Comment by aleksfront** [comment]
> > > Looks good, though on bigSur it doesn't seem to be changing colours (in your gif)
> > 
> > 
> > Yep, I suggest all colors will be white regardless of selected theme.
> 
> Why do we want that? That seems like the opposite of how it works on Catalina

This is not our will. Not only our icon always white but all other application's also. That's how Big Sur works since they changed menu line background with semi-transparent color placed over desktop bg image.

**Pull request merged**
