### PR TITLE
Revert "Remove requirement for JSON of messages"

### PR DESCRIPTION
**Pull request by jansav**
Reverts lensapp/lens#7426

Reverting as there was no motivation (at least written) to remove this quality of life feature

### CODE REVIEW

**Review by Nokel81 — CHANGES_REQUESTED** [review]
JSON is not required. See all the previous discussions.

Enforcing actions should be done by configuration of the mobx library not by messing with external checks

**Comment by jansav** [comment]
> See all the previous discussions.


Which one?

**Comment by jansav** [comment]
> Enforcing actions should be done by configuration of the mobx library not by messing with external checks

If something doesn't work at all, then for sure there has to be a check for it. Imagine trying to use something that doesn't work without reactive context and try to debug a reason if it doesn't tell you.

**Comment by Nokel81** [comment]
> If something doesn't work at all, then for sure there has to be a check for it. Imagine trying to use something that doesn't work without reactive context and try to debug a reason if it doesn't tell you.

If in a non reactive context it should just get the current state.  There are use cases for this.

**Comment by Nokel81** [comment]
> Which one?

On slack about how channels are not JSON serialized at all

**Pull request closed without merging**
