### PR TITLE
Release/v5.3.3

### PR DESCRIPTION
**Pull request by Nokel81**
## 🐛 Bug Fixes
Fix light theme pin icon visibility (**#4477**) https://github.com/aleksfront
add debug for locating startup issues (**#4481**) https://github.com/jim-docker
Don't emit build_id metadata on RPM builds (**#4464**) https://github.com/Nokel81
catch app.getPath() errors (when standard platform paths are missing) (**#4492**) https://github.com/jim-docker
Fix IngressApi being registered with a wrong new apiBase (**#4485**) https://github.com/Nokel81
Fixes a typo in kubeconfig sync "add"-button label (**#4522**) https://github.com/msa0311
Fix freeze after closing terminal on windows (**#4536**) https://github.com/Nokel81
Fix crash in ClusterStatus (**#4533**) https://github.com/Nokel81

### CODE REVIEW

**Comment by jim-docker** [comment]
#4421, #4452, #4483 (which was probably introduced by #4452?), #4537, and #4534 don't seem like bug fixes, are they necessary for this patch release?

**Comment by Nokel81** [comment]
I think the last one counts as a bug fix, but yes maybe the others don't

**Comment by jim-docker** [comment]
> I think the last one counts as a bug fix, but yes maybe the others don't

I see, but you managed to sneak in an unrelated loading display to the sidebar

**Comment by Nokel81** [comment]
@jim-docker removed https://github.com/lensapp/lens/pull/4392 https://github.com/lensapp/lens/pull/4537 https://github.com/lensapp/lens/pull/4421 https://github.com/lensapp/lens/pull/4452 and https://github.com/lensapp/lens/pull/4483 from this release

**Comment by jim-docker** [comment]
> I think the last one counts as a bug fix, but yes maybe the others don't

Did you end up not including that one (#4534)? I don't see it in the description (which is OK by me)

**Comment by Nokel81** [comment]
Yes I decided to remove that one and mark it as 5.4.0

**Review by jim-docker — APPROVED** [review]
tested on Windows

**Review by jakolehm — APPROVED** [review]

**Pull request merged**
