### PR TITLE
Fix: editing resource is broken when another resource is being editing

### PR DESCRIPTION
**Pull request by ixrock**
Regression from #2279

_Before:_

https://user-images.githubusercontent.com/6377066/111774474-2c170c00-88b8-11eb-83e3-cdccc906ec3f.mov

_After:_

https://user-images.githubusercontent.com/6377066/111774876-b9f2f700-88b8-11eb-9109-65f80c88b6c1.mov

### CODE REVIEW

**Review by Nokel81 — APPROVED** [review]

**Review by aleksfront — APPROVED** [review]
LGTM

**Comment by jim-docker** [comment]
This seems weird:

https://user-images.githubusercontent.com/40840436/111790787-f44c9c00-8898-11eb-9eff-b6e46fe440c2.mov

Cursor is placed at bottom of source in the second editor, and when you go back to the first editor, cursor has moved to the bottom there too.

**Comment by ixrock** [comment]
> Cursor is placed at bottom of source in the second editor, and when you go back to the first editor, cursor has moved to the bottom there too.

Good catch! 
Looks like a timing issue for restoring cursor in `ace-editor` on tab switching / componentDidUpdate.

**Comment by ixrock** [comment]
@jim-docker it seems like that behaviour happens only in case for first opened tab for editing (cursor position at `0:0`, then it jumps to the end line for follow-up tabs for for editing). But, actually it doesn't matter since those resources haven't been edited yet and cursor position not saved before. Otherwise I guess it works as expected, last cursor positions are restored per tab on select. Please see the video:

One thing could be improved probably, if we always keep position for freshly opened resources for editing at line 0:0 instead of jumping to the end of contents? (not critical imo)

https://user-images.githubusercontent.com/6377066/112126486-2b8ab800-8bcd-11eb-9dad-110e0e5ed05b.mov

**Comment by Nokel81** [comment]
@ixrock Can you please log a bug with that, I think we should fix it so that it doesn't jump around but I agree that it isn't that critical.

**Comment by ixrock** [comment]
> @ixrock Can you please log a bug with that, I think we should fix it so that it doesn't jump around but I agree that it isn't that critical.

Done ^

**Pull request merged**
