### PR TITLE
Release/v5.2.6 beta.0

### PR DESCRIPTION
**Pull request by jim-docker**
This PR also contains a commit to get the appropriate version of lens-ide for the 5.2 branch, which is not part of the changelog

## 🚀 Features

- Use random api prefix on kubectl-proxy (#4137) @jakolehm
## 🐛 Bug Fixes

- Remove cors headers from LensProxy (#4126) @jakolehm
- Electron 13.4.0 (#3820) @jakolehm

### CODE REVIEW

**Comment by jim-docker** [comment]
I added only PR's marked with the `area/security` label. This PR is mostly to test whether lens pulls in the right version of the spaces extension. More bug fixes can be added.

**Review by Nokel81 — APPROVED** [review]
I think that having just a security patch release to start is a good idea.

**Comment by jakolehm** [comment]
Are we sure that Electron 13.4.0 does not cause issues?

**Comment by jim-docker** [comment]
I was just looking at https://github.com/lensapp/lens/pull/3925, probably should bring it in too

**Pull request merged**
