### PR TITLE
Generate API Reference documentation using typedocs and gh-actions

### PR DESCRIPTION
**Pull request by msa0311**

### CODE REVIEW

**Comment by stevejr** [comment]
@jakolehm - All looks good to me. if you are ok with the yarn.lock updates can you merge?

**Comment by jakolehm** [comment]
@msa0311 could you squash (and sign) commits so that DCO bot is happy?

**Review by stevejr — COMMENTED** [review]
LGTM

**Review by jakolehm — APPROVED** [review]
LGTM (but we need to fix DCO stuff)

**Comment by msa0311** [comment]
Will create new pull request with signoff and a single commit to fulfil DCO bot rules

**Pull request closed without merging**
