### PR TITLE
Bump lens-k8s-proxy to v0.1.5

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Review by jakolehm — APPROVED** [review]
LGTM

**Review by jim-docker — COMMENTED** [review]
I see this when connecting to any cluster:
```
[0] error:   ▪ [CLUSTER]: Failed to connect to "minikube": StatusCodeError: 404 - "404 page not found\n" +2s
[0] error:   ▪ [LENS-PROXY]: Could not find cluster for upgrade request from url=/ws +2s
[0] error:   ▪ [LENS-PROXY]: Could not find cluster for upgrade request from url=/ws +3s
```
(and connection fails)

**Comment by Nokel81** [comment]
Did you clear out the old version from your `binaries` folder?

**Comment by jim-docker** [comment]
> Did you clear out the old version from your `binaries` folder?

`make dev` doesn't do that? I'll do a clean and try again

**Comment by Nokel81** [comment]
No, all it does it verify that the binary exists and if not downloaded the version specified.

I think we should be able to have it check if the checksums are correct and if not then delete and try again, but that hasn't been implemented yet.

**Review by jim-docker — APPROVED** [review]

**Pull request merged**
