### PR TITLE
Make default catalog action to open entity

### LINKED ISSUE #3909: Change Catalog default action of Entity to "open"
In order to make catalog more intuitive, lets change the catalog so that the default action will immediately open / connect to the Cluster / WebLink. 

Add the details panel as a link to the burger menu (three dots) as "Details".

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #3909

https://user-images.githubusercontent.com/8225332/135346594-cf47ff93-24dd-46e9-82ee-42835576a984.mov

### CODE REVIEW

**Comment by jweak** [comment]
Code looks good, but integration tests are failing.

**Comment by Nokel81** [comment]
@jweak Yeah... I noticed that after I finished yesterday. It will be easy to fix as they are failing because I changed the way you open clusters

**Review by jweak — APPROVED** [review]
👍

**Comment by jim-docker** [comment]
Wondering if we need the onRun action associated with clicking on the entity icon on the details page any more.

**Pull request merged**
