### PR TITLE
Fix broken hotbar switcher

### LINKED ISSUE #5167: Broken hotbar switcher
```
Cannot read properties of undefined (reading 'activeHotbarIndex')
```
error happens when trying to change Hotbar from the Hotbar switcher.

https://user-images.githubusercontent.com/9607060/161257710-098ff8ab-a564-45f0-940c-a949551cda23.mov

### PR DESCRIPTION
**Pull request by aleksfront**
Fixes #5167 

https://user-images.githubusercontent.com/9607060/161502976-f6298b00-95cc-4ffc-aabd-f4cab3ff0b24.mov

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

**Review by DmitriyNoa — DISMISSED** [review]

**Comment by aleksfront** [comment]
@Nokel81 Set 5.5.0 milestone since it's fixed regression from #5084 which won't go into 5.4.5

**Review by Nokel81 — DISMISSED** [review]

**Review by Nokel81 — COMMENTED** [review]
Actually, is this really the best solution? Wouldn't it be better to just not treat methods as free functions at the use?

**Comment by aleksfront** [comment]
> Actually, is this really the best solution? Wouldn't it be better to just not treat methods as free functions at the use?

Can you elaborate this a bit?

**Comment by Nokel81** [comment]
> Can you elaborate this a bit?

Sure, I meant to ask "would it be better to switch the uses of `hotbarStore.switchToPrevious` in `src/renderer/components/hotbar/hotbar-selector.tsx` to `() => hotbarStore.switchToPrevious()` instead of changing `switchToPrevious` from a method to a field function?"

**Comment by aleksfront** [comment]
@Nokel81 Made suggested changes

**Review by DmitriyNoa — APPROVED** [review]

**Review by Nokel81 — APPROVED** [review]

**Pull request merged**
