### PR TITLE
Fix CRD versions not being provided

### LINKED ISSUE #2438: After Upgrade to 4.2.0 - got error
**Describe the bug**
Incrementally upgraded to version 4.2.0. After upgrade completed, tried to run application and then got error as shown below.

**Expected behavior**
After upgrade to 4.2.0 expected to work app without errors.

**Screenshots**
Screen Shot 2021-04-02 at 11 42 58

**Environment (please complete the following information):**
- Lens Version: 4.2.0
- OS: Mojave 10.14.5 (18F132)
- Installation method (e.g. snap or AppImage in Linux): direct .dmg installation

**Logs:**
I have replaced apiUrl with [REDACTED] to hide info.

```
info: 📟 Setting Lens as protocol client for lens://
info: 📟 succeeded ✅
info: 🚀 Starting Lens from "/Users/samundra/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/lens-user-store.json
info: 🔑 Getting free port for LensProxy server
info: [CLUSTER-MANAGER]: init cluster {"id":"6afbf7d7-0b03-4f10-87b0-93adf7b1a9ab","name":"uat.test.io","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"b1f38fb6-9cb6-44c9-aef3-a0f2c918f370","name":"qa.test.io","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee","name":"prod.test.io","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at http://localhost:56830
info: 🔎 Testing LensProxy connection ...
info: ⚡ LensProxy connection OK
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/samundra/Library/Application Support/Lens
info: [CLUSTER]: "uat.test.io" init success {"id":"6afbf7d7-0b03-4f10-87b0-93adf7b1a9ab","context":"uat.test.io","apiUrl":"[REDACTED]"}
info: [CLUSTER]: "qa.test.io" init success {"id":"b1f38fb6-9cb6-44c9-aef3-a0f2c918f370","context":"qa.test.io","apiUrl":"https://api.qa.test.io"}
info: [CLUSTER]: "prod.test.io" init success {"id":"d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee","context":"prod.test.io","apiUrl":"https://api.prod.test.io"}
info: [EXTENSION-INSTALLER] installing dependencies at /Users/samundra/Library/Application Support/Lens
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:56830 ...
info: [EXTENSION-INSTALLER] dependencies installed at /Users/samundra/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/samundra/.k8slens/extensions
info: [EXTENSION]: enabled lens-license@0.1.0
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json
info: [EXTENSION]: enabled lens-survey@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from /Users/samundra/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: [WINDOW-MANAGER]: Main window loaded
info: 📡 Checking for app updates
info: Checking for update
info: [CLUSTER]: activate {"id":"d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee","name":"prod.test.io","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee","name":"prod.test.io","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee","name":"prod.test.io","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee" {"data":"Authentication proxy started\n","meta":{"id":"d26e0914-3d7d-4818-84a7-4a8bd3e6e4ee","name":"prod.test.io","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
info: Update for version 4.2.0 is not available (latest version: 4.2.0, downgrade is disallowed).
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
info: [STORE]: SAVING /Users/samundra/Library/Application Support/Lens/lens-cluster-store.json
(node:8048) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
this was working fine before upgrade. No change in kubeconfig.
``

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton<sebastian@malton.name>

fixes #2438

### CODE REVIEW

**Review by jakolehm — APPROVED** [review]
LGTM. Would few tests make sense here?

**Comment by Nokel81** [comment]
Yeah, tests would probably be a good idea.

**Comment by jakolehm** [comment]
I think this PR should target `master`  because the issue is also there, right?

**Comment by Nokel81** [comment]
@jakolehm that is what I meant by the `merge/master` label. It is a note to myself to cherry pick this onto Master (as a PR) after this is merged.

**Review by nevalla — APPROVED** [review]

**Pull request merged**
