### PR TITLE
Fix Catalog being empty after subsequent opens

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Comment by jakolehm** [comment]
@Nokel81 could you describe the problem a bit and how this fixes it?

**Comment by Nokel81** [comment]
Yes, do the following on master: 

1. Run `make dev`
2. View the catalogue 
3. See kube sync items
4. Close window
5. Reopen window from tray
6. View the catalogue 
7. See empty list

**Comment by ixrock** [comment]
> Yes, do the following on master:
> 
> 1. Run `make dev`
> 2. View the catalogue
> 3. See kube sync items
> 4. Close window
> 5. Reopen window from tray
> 6. View the catalogue
> 7. See empty list

Haha, this is fun, you noticed this in my `mobx6-migration` branch, but it was broken in master :D
Btw, fix was just to add this:

```ts
  ipcMain.on(IpcRendererNavigationEvents.LOADED, () => {
    // this is moved from the top initialization in main/index.ts
    KubeconfigSyncManager.createInstance().startSync();
```

**Comment by jakolehm** [comment]
@Nokel81 do we really need all these changes for a fix? And why don't we target `master` branch for a fix?

**Comment by Nokel81** [comment]
@jakolehm No we don't really need all of these. I probably should have made two PRs.

As to why not targeting master? I am targeting future master as I would like get all these PRs in.

**Comment by Nokel81** [comment]
Just the bug fix is now in #2815 I'll keep this as a cleanup PR.

**Comment by Nokel81** [comment]
Closing this, will make a new PR with just the cleanups.

**Pull request closed without merging**
