### PR TITLE
Force update after thirty days since update was downloaded

### LINKED ISSUE #5208: Must upgrade immediately modal
**What would you like to be added**:
If Lens has been running for a long time with an update downloaded and pending then a modal should be displayed requiring the user to quit so that the update can be applied.

### PR DESCRIPTION
**Pull request by jansav**
image

**What:**

Force updating of application when 30 days has gone since update was downloaded. 

**Why:**

Some users keep the application open "forever" and therefore never get updates.

### CODE REVIEW

**Comment by disconn3ct** [comment]
Is this related to the workarounds in https://github.com/lensapp/lens/issues/5444 ? Why is the capability to force an update more important than the ability to use the app without signing in? This looks like an escalation.

It has been more than a 'few days'  and the situation is unchanged (except for actions like this, which 'accidentally' block workarounds.)

https://github.com/lensapp/lens/issues/5444#issuecomment-1144783199

**Comment by PhilippKuntschik** [comment]
> Is this related to the workarounds in #5444 ? Why is the capability to force an update more important than the ability to use the app without signing in? This looks like an escalation.
> 
> It has been more than a 'few days' and the situation is unchanged (except for actions like this, which 'accidentally' block workarounds.)
> 
> [#5444 (comment)](https://github.com/lensapp/lens/issues/5444#issuecomment-1144783199)

as discussed [in the issue ](https://github.com/lensapp/lens/issues/5208) that this merge request solves, there is no implication on #5444 since the "forced update" will only point to the propritary Mirantis Lens, if you are already using the propritary Mirantis Lens.

**Comment by MuhammedKalkan** [comment]
> > Is this related to the workarounds in #5444 ? Why is the capability to force an update more important than the ability to use the app without signing in? This looks like an escalation.
> > It has been more than a 'few days' and the situation is unchanged (except for actions like this, which 'accidentally' block workarounds.)
> > [#5444 (comment)](https://github.com/lensapp/lens/issues/5444#issuecomment-1144783199)
> 
> as discussed [in the issue ](https://github.com/lensapp/lens/issues/5208) that this merge request solves, there is no implication on #5444 since the "forced update" will only point to the propritary Mirantis Lens, if you are already using the propritary Mirantis Lens.

That is not entirely true, In this comment https://github.com/lensapp/lens/issues/5208#issuecomment-1173776720 he says 'if update not configured'.
At open builds repo, update is configured. We will see how it affects build artifacts

**Comment by disconn3ct** [comment]
The proprietary Lens product is the one that most users will use, and it is the one that your users are explicitly asking to **not** auto-update until the other privacy issues are resolved. That sounds very related to me. Forced auto-update wasn't a need until your users started rejecting updates, which was a direct result of #5444 .

**Comment by PhilippKuntschik** [comment]
> The proprietary Lens product is the one that most users will use, and it is the one that your users are explicitly asking to **not** auto-update until the other privacy issues are resolved. That sounds very related to me. Forced auto-update wasn't a need until your users started rejecting updates, which was a direct result of #5444 .

Proprietary Lens is the one most user use _today_. I expect that most people that do not require enterprise support will switch to OpenLens as soon as it is available, which is a win-win: Mirantis has better numbers on billable customers, and the community has an OpenSource project that does not inject any additional logic such as LensSpace etc.

**Comment by disconn3ct** [comment]
Trying to pretend that a change to FORCE UPGRADES  is unrelated to the bug where users are choosing to NOT UPGRADE is not a stretch I can manage without some warmups first.

> I expect that most people that do not require enterprise support will switch to OpenLens as soon as it is available, which is a win-win

That assumes that they will merge (and maintain) that PR now that it has been submitted. We'll need to wait to see if it has the urgency of this PR. (If I was a betting person...)

More critically though, you are assuming they want lots of 'quality' users,  and that pushing 'unsuitable' users to the free version is a good thing. That isn't the only (or best) match to their behavior. Alternate guess: they want lots of registered users to meet a metrics goal, and don't care as much about how many of those people are real or happy about it. From the outside, it appears that the health and optics of the app itself are not of much concern if this goal can be met in the short term.

(Pure speculation, but maybe they "just" want a huge email list that they can say is legit opt-in fresh and hot. Lots of weird metrics become critical during fundraising, acquisitions, etc etc.)

**Comment by PhilippKuntschik** [comment]
> Trying to pretend that a change to FORCE UPGRADES is unrelated to the bug where users are choosing to NOT UPGRADE is not a stretch I can manage without some warmups first.
> 
> > I expect that most people that do not require enterprise support will switch to OpenLens as soon as it is available, which is a win-win
> 
> That assumes that they will merge (and maintain) that PR now that it has been submitted. We'll need to wait to see if it has the urgency of this PR. (If I was a betting person...)
> 
> More critically though, you are assuming they want lots of 'quality' users, and that pushing 'unsuitable' users to the free version is a good thing. That isn't the only (or best) match to their behavior. Alternate guess: they want lots of registered users to meet a metrics goal, and don't care as much about how many of those people are real or happy about it. From the outside, it appears that the health and optics of the app itself are not of much concern if this goal can be met in the short term.
> 
> (Pure speculation, but maybe they "just" want a huge email list that they can say is legit opt-in fresh and hot. Lots of weird metrics become critical during fundraising, acquisitions, etc etc.)

This discussion gets out of hand and should be migrated away from this pull request since it does not contain any technical information. That said, this feature is discussed as security improvement and I am willing to believe this argumentation. You can also see that this issue has i) draft status, and ii) not even a valid description defining the architecture which makes me believe that this is by no means an "urgent" merge request, but rather a way for the devs to manage their progress. Furthermore we can all speculate about the intentions of Mirantis behind their LensID but clearly this is all not part of this very MIT licensed Opensource project.

**Comment by PhilippKuntschik** [comment]
@jansav what happens if there is no update available for thirty days?

**Comment by jansav** [comment]
> @jansav what happens if there is no update available for thirty days?

This modal is shown when **update has been downloaded** but not installed within 30 days. Very marginal use case. 
That being said, nothing will happen.

**Comment by marafa-sugarcrm** [comment]
where is the preference to change this setting?
will it be called "Disable force update" ?

**Review by Nokel81 — DISMISSED** [review]

**Review by Nokel81 — APPROVED** [review]

**Comment by jim-docker** [comment]
Updating/auto-updating relies on a source being set for locating updates. By default in this repo there is no source set. Hence, built as is, there is no checking for updates or autoupdating. As part of our build process, Mirantis adds update source information for the Mirantis lens-ide releases. Similarly, as part of their build process, the community could theoretically add update source information for the community OpenLens releases. The community version maintainers can control whether their releases use the in-app update facility, and if so, what the source of those updates is.

@disconn3ct @PhilippKuntschik @marafa-sugarcrm

**Comment by disconn3ct** [comment]
> You can also see that this issue has i) draft status, and ii) not even a valid description defining the architecture which makes me believe that this is by no means an "urgent" merge request

Guess what got merged before the build PR even got a preliminary review...

Edit: and released seconds later. Conveniently just over 30 days after the forced login.. Do you actually believe this is a coincidence? Honest question because I'm really not seeing it that way.

**Comment by PhilippKuntschik** [comment]
@disconn3ct I still think this feature can be useful if the enduser is able to set the update channel via settings (or leave it blank). I found the respective settings-pointer where the update channel is set in the repository here: https://github.com/lensapp/lens/blob/b414f9e06d28a6e3327dfdd1ff8e0a888e5709b1/src/common/application-update/update-channels.ts#L26-L30

@jansav @Nokel81 for the MIT licensed open source project, this should point to the projects repository release page, am I right?

**Comment by msa0311** [comment]
Hello Everyone,

with this next release we will massively improve the user experience for the update mechanism. It is now way more transparent for the user as we have all the relevant steps in the tray icon visualised. From our point of view the OpenLens repository is the right place to improve this as the update mechanism is depending on Electron. 

Addressing your concern regards the Open Source Binary built that we might have in the future (if we can find a conclusion and a maintainer team): This is not going to affect this binary because we would just not set the publishing source. 

Hope this helps!

**Comment by PhilippKuntschik** [comment]
@msa0311, there is no _concern_ but a way to make this feature useful. If the publishing source is set to the release section of this repository, the OpenLens build _does_ benefit from this feature; otherwise it would be dead code. For the Mirantis-build the publishing source would just be overwritten.

**Comment by msa0311** [comment]
Sure, if someone is paying for the Code Signing certificates that could be an option as well.

**Comment by PhilippKuntschik** [comment]
> Sure, if someone is paying for the Code Signing certificates that could be an option as well.

Can you elaborate what this has to do with a code signing certificate?

**Comment by disconn3ct** [comment]
> > Sure, if someone is paying for the Code Signing certificates that could be an option as well.
> 
> Can you elaborate what this has to do with a code signing certificate?

Its an excuse to not have to publish the un-spyware OSS version for any platform, regardless of walled-gardens. (And don't they already have a code signing cert for the ~spyware~ closed source version?)

Is that super minor expense really the hill Mirantis wants to go down on? Cuz this lends itself super nicely to twitter. Its easy to cast doubt on spywhere when the company is working so hard to make it look super sketchy..

**Comment by PhilippKuntschik** [comment]
> > > Sure, if someone is paying for the Code Signing certificates that could be an option as well.
> > 
> > 
> > Can you elaborate what this has to do with a code signing certificate?
> 
> Its an excuse to not have to publish the un-spyware OSS version for any platform, regardless of walled-gardens. (And don't they already have a code signing cert for the ~spyware~ closed source version?)
> 
> Is that super minor expense really the hill Mirantis wants to go down on? Cuz this lends itself super nicely to twitter. Its easy to cast doubt on spywhere when the company is working so hard to make it look super sketchy..

@dis your comment is not constructive and not helping. I would like to hear from Mario what he has to say. I don't say that I disagree but your comment does not leave any room for them to explain how they see the situation ending without losing face. I understand you are angry and want to blame someone, but that was just the wrong moment to do so.

**Comment by disconn3ct** [comment]
> without losing face

What does "don't make them feel bad" have to do with the situation? In all seriousness. I'm not a fan of "pretend it didn't happen". So far, the official responses have been "we'll make this not mandatory" and then a bunch of work to make it as mandatory as possible as quickly as possible. I feel that is hard to misinterpret, but I'm all ears if anyone has an alternate explanation that fits all of the mess over the 4ish tickets.

The code signing certificate looks like a red herring. Doesn't Apple still give unlimited certificates to each and every developer account? Do they not have **any** Apple developer accounts to sign the spyware Lens with? That seems harder to believe than thinking "we doubt any OSS users will fork over $100/yr for us"

(Edit to add: It looks like the message from Jan-Otto Kröpke saying they would fix it ASAP was deleted after it was posted; at least, I can find it in my email but no longer in the thread. Another bad look if it isn't just github being broken.)

**Comment by PhilippKuntschik** [comment]
@disconn3ct I am trying to build bridges that connect the walls created by both the community and the corporate. It's just not getting easier if you put stone upon stone to make the wall higher and higher.

If you want to have a solution, we have to start to work towards each other again, allow to trust each other again. Otherwise all this discussion is lost time and I (for me at least) will not only blame corporate for that.

**Comment by msa0311** [comment]
@PhilippKuntschik good comments.

Afaik Electron requires properly signed binaries for the built-in update mechanism to work at all.

I dont think the pricing of the signing certificates is a big deal. More important would be someone again to observe and maintain the expiration and renewal of those certificates.

**Comment by marafa-sugarcrm** [comment]
> > @jansav what happens if there is no update available for thirty days?
> 
> This modal is shown when **update has been downloaded** but not installed within 30 days. Very marginal use case. That being said, nothing will happen.

was the download in the background? did the user agree to use up his bandwidth for this download? 

as a person who once lived on a limited monthly bandwidth i'd like to make that decision myself. and i am sure others in the same situation would like to best optimize their use of their own **_paid_** bandwidth

**Comment by jskrzypek** [comment]
@PhilippKuntschik YMMV, but in my experience forced upgrades (and automatic upgrades too) are actually a security _nightmare_ for an OSS project, not a security _feature_. They provide a vehicle for abuse by malicious actors, without allowing users to have a simple workaround of not accepting the upgrade.

**Pull request merged**
