### PR TITLE
Add Check-For-Updates in menu and some notifications

### LINKED ISSUE #4380: Check for updates option in the top menu
Would be nice to have an option for manual checking for updates as `vscode` does:

Screenshot 2021-11-18 at 16 17 39
Screenshot 2021-11-18 at 16 17 21

In addition we could auto-check new version when opening `About Lens` similarly as done in `chrome`:
Screenshot 2021-11-18 at 16 22 28
Screenshot 2021-11-18 at 16 24 23

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/4380
Screen Shot 2021-11-26 at 10 14 03 AM
Screen Shot 2021-11-26 at 10 13 27 AM

### CODE REVIEW

**Review by jweak — APPROVED** [review]
Looks good!

**Comment by aleksfront** [comment]
Looks good, however, I can't reproduce notification to appear since I can't make this work
```
export function isAutoUpdateEnabled() {
  return autoUpdater.isUpdaterActive() && isPublishConfigured;
}
```

built app with both `yarn build:mac`, `yarn dist` with no luck - "Check for updates" menu not visible. Did something wrong?

**Comment by Nokel81** [comment]
> Looks good, however, I can't reproduce notification to appear since I can't make this work
> 
> ```
> export function isAutoUpdateEnabled() {
>   return autoUpdater.isUpdaterActive() && isPublishConfigured;
> }
> ```
> 
> built app with both `yarn build:mac`, `yarn dist` with no luck - "Check for updates" menu not visible. Did something wrong?

You need to be able to sign your binaries and you need to upload a newer version of said signed binary to some provider. I have been using the staging S3 account.

**Comment by jakolehm** [comment]
@Nokel81 maybe we could move "Checking for updates" notification text to bottom/status bar. It's a bit annoying at the moment because it appears every time app starts. Alternatively we could just not show it on app start.

**Comment by Nokel81** [comment]
Moving to the status bar sounds like a great idea.

**Pull request merged**
