### PR TITLE
Adding menu accelerators for basic actions

### PR DESCRIPTION
**Pull request by aleksfront**
Adding keyboard menu accelerators for Preferences (`CmdOrCtrl+,`), Cluster Settings (`CmdOrCtrl+Shift+S`) and Add Cluster (`CmdOrCtrl+Shift+A`) pages.

file menu
mac menu

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

**Comment by Nokel81** [comment]
Can you also add accelerators for closing the window and for opening the window back up (maybe only on macos)

**Review by ixrock — APPROVED** [review]
LGTM

**Comment by ixrock** [comment]
BTW, is it not triggered when mouse focused within some `<Input/>`, right?

**Comment by aleksfront** [comment]
> BTW, is it not triggered when mouse focused within some `<Input/>`, right?

No, menu key accelerators are triggered no matter what is focused at the moment.

**Comment by aleksfront** [comment]
> Can you also add accelerators for closing the window and for opening the window back up (maybe only on macos)

My suggestion is to open a separate issue for `Close Window` action if needed - it may have couple of questions and possible discussion.

Do we have some example for such an action? I see through few apps that `Close Window` mechanism isn't cosistent (e.g. there's no key accelerator for restoring a window). And we already have `Hide Lens (Command + H)` in the main menu which does pretty same action since we can have only 1 window opened at the moment.

**Pull request merged**
