### PR TITLE
Fix Windows tray icon click

### PR DESCRIPTION
**Pull request by jakolehm**
On Windows it's common that clicking a tray icon opens the app window. Currently click does nothing which feels like a bug.

### CODE REVIEW

**Comment by Nokel81** [comment]
I don't agree that this is always the case, take for instance the `Bluetooth` tray icon for windows 10. Clicking it brings up a menu which you then have to click something else to open the Bluetooth settings window.

**Comment by jim-docker** [comment]
> I don't agree that this is always the case, take for instance the `Bluetooth` tray icon for windows 10. Clicking it brings up a menu which you then have to click something else to open the Bluetooth settings window.

It certainly varies what happens but it's probably better to do something than nothing

**Comment by Nokel81** [comment]
Does the tray menu not get opened on Windows like it does on Linux and macOS?

**Comment by jim-docker** [comment]
On Windows Lens tray icon right click brings up context menu, left click does nothing

**Review by Nokel81 — APPROVED** [review]

**Review by nevalla — APPROVED** [review]

**Pull request merged**
