### PR TITLE
Update kubectl to v1.21.2

### LINKED ISSUE #541: Port-Forwarding does not keep connection alive
**Describe the bug**
Port-Forwardings get broken after a few minutes if there is no traffic.

**To Reproduce**
1. Start port-forwarding of HTTP service
2. Open browser and ensure it's working
3. Relead browser tab after 5 minutes or so

**Expected behavior**
Port-Forward is kept alive or is automatically recreated

**Environment (please complete the following information):**
- Lens Version: 3.5.0
- OS: Win 10 x64 Prof 1819

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes https://github.com/lensapp/lens/issues/541

### CODE REVIEW

**Comment by jakolehm** [comment]
After testing this a bit more it seems that we still have issues.

**Review by jim-docker — DISMISSED** [review]
Was there a reason why we weren't already bundling newer than 1.18?

**Review by nevalla — DISMISSED** [review]

**Comment by nevalla** [comment]
Do I remember wrong, but do we have any issues open that this PR will fix, something related to proxy settings?

**Comment by jakolehm** [comment]
> Do I remember wrong, but do we have any issues open that this PR will fix, something related to proxy settings?

As mentioned in the PR description this should fix #541 🙂

**Comment by jakolehm** [comment]
@nevalla ptal again.

**Comment by nevalla** [comment]
> > Do I remember wrong, but do we have any issues open that this PR will fix, something related to proxy settings?
> 
> As mentioned in the PR description this should fix #541 🙂 

🙈

**Review by nevalla — APPROVED** [review]

**Pull request merged**
