### PR TITLE
Update all links within application

### PR DESCRIPTION
**Pull request by Nokel81**
- URLs removed the /latest/ and /main/ pathname prefixes

Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Comment by jim-docker** [comment]
`README.md` has some links

**Comment by Nokel81** [comment]
@jim-docker Readme is covered by #6441

**Comment by jim-docker** [comment]
> @jim-docker Readme is covered by #6441

duh

**Review by jim-docker — APPROVED** [review]
LGTM

**Pull request merged**
