### PR TITLE
fix(renderer-log): multiple spaces merge into one

### PR DESCRIPTION
**Pull request by BlackHole1**
before:
图片

after:
图片

### CODE REVIEW

**Comment by Nokel81** [comment]
does this fix #2412?

**Review by Nokel81 — APPROVED** [review]

**Comment by BlackHole1** [comment]
> does this fix #2412?

I took a look and found that this PR cannot solve this problem 100%, but the situation will improve.

**Comment by Nokel81** [comment]
Thanks for checking.

**Comment by BlackHole1** [comment]
I will take a closer look at the problem tomorrow. Personally, I think it should be easier to fix. If I find a solution, I will submit a new PR.

**Review by jakolehm — APPROVED** [review]

**Comment by BlackHole1** [comment]
hi @Nokel81 , I just wrote a test demo and found that this PR can fix #2412 .

before:
图片

after:
图片

my test code:

```golang
package main

import (
	log "github.com/sirupsen/logrus"
	"os"
)

func main() {
	log.SetFormatter(&log.TextFormatter{
		ForceColors:            true,
		FullTimestamp:          true,
		DisableLevelTruncation: true,
		PadLevelText:           true,
	})
	log.SetOutput(os.Stdout)
	log.SetLevel(log.TraceLevel)

	log.Error("this is error log")
	log.Warning("this is warning log")
	log.Info("this is info log")
	log.Debug("this is debug log")
	log.Trace("this is trace log")
}

```

**Comment by Nokel81** [comment]
Excellent thank you.

**Pull request merged**
