### PR TITLE
Don't recreate the whole userExtensions Map on every change

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

This is a similar solution to what was done with the instances by name mapping.

### CODE REVIEW

**Comment by nevalla** [comment]
When trying to enable / disable an extension I get this error:
image

**Comment by Nokel81** [comment]
@nevalla Thanks for that report, I forgot to test that flow.

**Comment by nevalla** [comment]
There seems to be still some issues on disabling/enabling extensions:

https://user-images.githubusercontent.com/455844/129727467-b0cdb10f-48eb-4992-8890-6b095abd9543.mov

**Comment by Nokel81** [comment]
After some more testing I don't think I can get this to work. Might come back to this later if need be.

**Pull request closed without merging**
