### PR TITLE
Amend the docs nav menu

### PR DESCRIPTION
**Pull request by stevejr**
Moved all the nav items up one layer

Signed-off-by: Steve Richards <srichards@mirantis.com>

### CODE REVIEW

**Review by Nokel81 — DISMISSED** [review]

**Comment by stevejr** [comment]
Blocked until #2898 is merged in

**Review by Nokel81 — APPROVED** [review]

**Comment by Nokel81** [comment]
@stevejr You should be able to merge master into this now.

**Comment by stevejr** [comment]
@jakolehm / @msa0311 - Can you review and approve so we can merge this in. Thanks

**Review by jim-docker — APPROVED** [review]

**Review by msa0311 — APPROVED** [review]

**Comment by stevejr** [comment]
@leenamba / @msa0311 - do we still want to change the Lens Extension docs title to `Lens Extension Development`?

**Pull request merged**
