### PR TITLE
Add distribution and version columns for KubernetesClusters

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

Same behaviour as https://github.com/lensapp/lens/pull/5611

### CODE REVIEW

**Comment by jakolehm** [comment]
@Nokel81 tests are failing.

**Comment by Nokel81** [comment]
@jakolehm yeah, will rebase to fix that shortly

**Comment by jim-docker** [comment]
deselecting the version and distro columns doesn't work:


https://user-images.githubusercontent.com/40840436/189031716-3cba1aa3-b511-498a-9afc-8560ea4dd72a.mov

**Comment by Nokel81** [comment]
@jim-docker Fixed

**Review by aleksfront — APPROVED** [review]
LGTM!

**Pull request merged**
