### PR TITLE
Add support for PodDisruptionBudgets

### PR DESCRIPTION
**Pull request by dan-slinky-ckpd**
This is a WIP for supporting `PodDisruptionBudgets`. I'd really appreciate some initial feedback if you can @jakolehm @nevalla

### CODE REVIEW

**Review by nevalla — APPROVED** [review]
Thanks. Looks awesome. Tested and works like a charm 🍻

**Comment by dan-slinky-ckpd** [comment]
changes rebased after the project restructuring

**Comment by nevalla** [comment]
@dan-slinky-ckpd Sorry for keep you waiting on this. Please could you resolve the conflict. `apiResources` are defined now in `src/common/rbac.ts` instead of `src/main/routes/config.ts`. After the conflict resolving we can finally merge this 🙏 .

**Comment by dan-slinky-ckpd** [comment]
@nevalla Updated and resolved.

**Pull request merged**
