### PR TITLE
New logo

### LINKED ISSUE #142: Application icon hard to read / lens should have a "real" logo
**What would you like to be added**:
I think, the icon that currently ships with Lens is not suited to represent the application.
- it is barely readable / understandable (especially in small sizes such as 16x16 or even 32x32)
- It does not contain any pictogram and basically contains only the text "Lens by Kontena"
- Kontena has ceased operations :-( -- even though I do believe, that it's name should be mentioned somehow, I have the feeling that the icon might be the wrong place

**Why is this needed**:
- Improve UX
- Establish a strong (app) brand

### PR DESCRIPTION
**Pull request by jakolehm**
image

image

Fixes #142

### CODE REVIEW

**Comment by nevalla** [comment]
Should we change it also on dashboard?

image

**Comment by jakolehm** [comment]
> Should we change it also on dashboard?

Yes, good point... let's see if I can make it happen.

**Comment by jakolehm** [comment]
Dashboard logo updated:
image

**Comment by jakolehm** [comment]
Now with a background:

image

**Comment by jakolehm** [comment]
Updated:
image

**Review by nevalla — APPROVED** [review]
LGTM

**Pull request merged**
