### PR TITLE
Fix Documentation: Using Helm Charts

### PR DESCRIPTION
**Pull request by stevenGravy**
Repositories was misspelled in Managing Helm Repositories

### CODE REVIEW

**Comment by Nokel81** [comment]
@stevenGravy Please sign your commit https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by stevenGravy** [comment]
> @stevenGravy Please sign your commit https://docs.pi-hole.net/guides/github/how-to-signoff/
@Nokel81 
I did a signoff and then attempted the  following :
```bash
$ git push --force-with-lease origin patch-2
remote: Permission to lensapp/lens.git denied to stevenGravy.
fatal: unable to access 'https://github.com/lensapp/lens/': The requested URL returned error: 403
```

**Comment by Nokel81** [comment]
Try just `--force`?

**Comment by stevenGravy** [comment]
> Try just `--force`?

@Nokel81 , thanks for the assist, will know for next time!

**Review by Nokel81 — APPROVED** [review]

**Review by nevalla — APPROVED** [review]

**Pull request merged**
