### PR TITLE
Correctly catch and notify user about NodeShell pod failures

### LINKED ISSUE #2687: Detect and notify when shell cannot be launched on node due to pod limit
**What would you like to be added**:

Currently Lens provides an option to run a shell on a node, which it does by launching a privileged pod on the node. On my non-production clusters, this frequently fails due to the node having already reached its pod limit, so there is no room for an additional pod. Currently when this happens there is no feedback from Lens about it, Lens just waits for the pod to come up, which it never does. 

I would like Lens to detect this condition, provide a notification of some kind, and not attempt to create the pod in this case. 

It would also be helpful to have some indication of pod count and limit on the "Nodes" display, as is done with CPU, Memory, and Disk.

**Why is this needed**:

Typically I can run a shell on any node in the cluster to accomplish my task, but when they are mostly full due to pod count, it is a lot of trial and error to find an available node, and in the meantime, Lens' failing pods are somewhat disruptive to the cluster.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: macOS

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2687

### CODE REVIEW

**Comment by aleksfront** [comment]
Should we create a new issue out of this (from #2687)
> It would also be helpful to have some indication of pod count and limit on the "Nodes" display, as is done with CPU, Memory, and Disk.

Because the issue actually contains 2 requests and we're fixing here only one.

**Comment by Nokel81** [comment]
We already have that https://github.com/lensapp/lens/issues/2680

**Comment by jim-docker** [comment]
Waiting > 10 mins:
Screen Shot 2021-11-04 at 4 42 10 PM

I have 110 running pods and I try to open a node-shell. It should timeout?

**Comment by Nokel81** [comment]
It should have given you a message and then closed itself. It did when I was testing it myself, will try again...

**Comment by Nokel81** [comment]
@jim-docker I think that is a different bug... weird though, because I cannot see where `this.xterm` would be `undefined` at that point will investigate.

**Comment by Nokel81** [comment]
@jim-docker That should be fixed now.

**Review by jim-docker — APPROVED** [review]

**Pull request merged**
