### PR TITLE
Fix Makefile to work on Windows dev env

### LINKED ISSUE #1563: Dev environment is broken on Windows
`make dev` produces errors and prevents to start

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #1563 

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

**Review by jakolehm — APPROVED** [review]

**Comment by jakolehm** [comment]
@nevalla CI says no:
```
if not exist ".\src\extensions\npm\extensions\dist\src\renderer\themes" mkdir .\src\extensions\npm\extensions\dist\src\renderer\themes
/usr/bin/bash: -c: line 1: syntax error: unexpected end of file
mingw32-make: *** [Makefile:82: copy-extension-themes] Error 1

```

**Comment by nevalla** [comment]
Let's see if quotas help here

**Comment by jakolehm** [comment]
> Let's see if quotas help here

Did not help.

**Review by jakolehm — CHANGES_REQUESTED** [review]
CI is failing.

**Pull request closed without merging**
