### PR TITLE
remove deprecated package request from our code

### LINKED ISSUE #459: Get rid of "request" and "request-promise-native" (deprecation notice)
Prerequisites:
https://github.com/request/request/issues/3142

Suggested replacement:
https://github.com/mikeal/bent

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <smalton@mirantis.com>

"request" has been deprecated since February 2020. See https://github.com/request/request/issues/3142

I have chosen "got" as it is a fully featured package that is quite small and uses promises (and typescript) as first class citizens. It also has a very good interaction with streaming files.

This PR doesn't yet remove request from `yarn.lock` because some other packages are still using it. 

Fixes #459

### CODE REVIEW

**Comment by ixrock** [comment]
Related issue https://github.com/lensapp/lens/issues/459

**Comment by Nokel81** [comment]
To simplify other work for 4.0.4, I am going to request that this gets reviewed and merged. I am going to fix the conflicts as well.

**Comment by Nokel81** [comment]
Moving this to 4.3 as it still requires a decent amount of work to get correct.

**Comment by Nokel81** [comment]
Closing this as I don't have the throughput to get this back to working. And I would have to do most of this work again from scratch anyway. Plus this really needs https://github.com/kubernetes-client/javascript/issues/414 to be resolved.

**Pull request closed without merging**
