### PR TITLE
Electron 12

### PR DESCRIPTION
**Pull request by jakolehm**
- https://www.electronjs.org/releases/stable?version=10&page=5#10.0.0
- https://www.electronjs.org/releases/stable?version=11&page=5#11.0.0
- https://www.electronjs.org/releases/stable?version=12&page=3#12.0.0

### CODE REVIEW

**Comment by Nokel81** [comment]
Is it possible to upgrade to node16 as well or is electron-12 not compatible with node-16?

**Comment by Nokel81** [comment]
Is electron-13 too new?

**Comment by LucaDev** [comment]
I don't think electron 13 is too new. I haven't heard of any major bugs and V8 got some nice performance improvements with chrome 91.

**Comment by Nokel81** [comment]
Closing in favour of #3572

**Pull request closed without merging**
