### PR TITLE
Add support for Prometheus api prefix

### LINKED ISSUE #258: Can't connect to existing prometheus service if prometheus has --web.route-prefix configured
**Describe the bug**
Within my k8s cluster, I have existing prometheus running and that prometheus container has `--web.route-prefix=/prometheus` argument on startup by some reason. That is to say the pod didn't listen to root path of `http://service-ip:port/` but `http://service-ip:port/prometheus`. As the result, Lens app couldn't connect to my existing prometheus to retrieve metrics for k8s cluster.

I compared requests between lens installed prometheus and my prometheus. Below are request to lens installed prometheus service.

image

While here was my prometheus. There difference between was service url prefix `/prometheus`

image

In addition, I've tried to configure that prefix through Lens settings of `Prometheus service address`. But it failed that the text box was restricted only with `namespace/service:port` pattern without any url prefix parameter.

**To Reproduce**
1. Add a cluster with existing prometheus.
2. Click` settings` of cluster and configure `prometheus service address`.
3. Go to cluster again to check `Overview` of cluster.
4. No metrics showed.

**Expected behavior**
Somehow, Lens supports Prometheus service not just expose through url root path `http://service-ip:port/` but with defined url prefix like `http://service-ip:port/prefix/`

**Screenshots**
Configured custom prometheus service

image

Lens overview didn't work after configure.

image
**Environment (please complete the following information):**
- Lens Version: Version: 3.2.0
- OS: OSX 10.14.6
- Installation method: Download .dmg file from release at <https://github.com/lensapp/lens/releases>
 
**Logs:**
No log file.

**Kubeconfig:**
kubeconfig didn't have problem since I can see all the function besides metrics of customer prometheus.

**Additional context**
NO.

### LINKED ISSUE #337: Prometheus endpoint as url
I use VictoriaMetrics as drop-in replacement for prometheus.
But it has url with some path in it.

So, it's not enough for me just host:port  in the settings.

### PR DESCRIPTION
**Pull request by nevalla**
This PR allows user to define prometheus API prefix along prometheus service address, for example: `default/prometheus-prometheus-oper-prometheus:9090/api`.

fixes #337, fixes #258

### CODE REVIEW

**Comment by vimhq** [comment]
Hello, I see an issue with this PR: prefixes with / symbol in it (such as /my/complex/prefix) won't work because / symbol is as a separator in split function.

**Comment by nevalla** [comment]
> Hello, I see an issue with this PR: prefixes with / symbol in it (such as /my/complex/prefix) won't work because / symbol is as a separator in split function.

Good point. I changed the implementation to take this into an account.

**Comment by jakolehm** [comment]
@nevalla this needs conflict resolve.

**Comment by nevalla** [comment]
> @nevalla this needs conflict resolve.

Done

**Review by jakolehm — APPROVED** [review]

**Pull request merged**
