### PR TITLE
Update Documentation: Getting Started

### PR DESCRIPTION
**Pull request by florianrusch**
Readd homebrew installation advice, which was someday in the root README.md of the project.

See also:
- https://github.com/lensapp/lens/pull/176
- https://github.com/lensapp/lens/pull/511
- https://github.com/lensapp/lens/pull/548

### CODE REVIEW

**Comment by florianrusch** [comment]
I will sign the commit later

**Comment by Nachasic** [comment]
Thank you for this contribution! If you're having trouble signing your commit, you can do it like this:
```
git commit --amend --signoff
git push --force
```

**Comment by florianrusch** [comment]
@ixrock @Nachasic I finally signed it. Had some trouble with an expired gpg key 🙈

**Review by Nachasic — APPROVED** [review]
LGTM

**Comment by msa0311** [comment]
Thanks for your help, but the docs have been migrated to Lens-IDE distribution and cannot be maintained as part of the open source repository from now on.

**Pull request closed without merging**
