### PR TITLE
Release 6.4.15

### PR DESCRIPTION
**Pull request by Nokel81**
## 🐛 Bug Fixes
- Stop file system watchers on application quit to prevent exit code !== 0 (**[#7504](https://github.com/lensapp/lens/pull/7504)**) https://github.com/jansav
- Fix loading system CAs on non-linux platforms (**[#7515](https://github.com/lensapp/lens/pull/7515)**) https://github.com/nokel81

### CODE REVIEW

**Comment by Nokel81** [comment]
NOTE: I have also cherry-picked https://github.com/lensapp/lens/pull/7424 onto this branch here as we no longer need it.

**Comment by jim-docker** [comment]
https://github.com/lensapp/lens/pull/7515 seems a bit big for a patch. Plus it was merged to master only an hour ago. How much testing has it had?

**Comment by Nokel81** [comment]
That PR is necessary to fix a critical bug where CAs are not being loaded.

It has been tested by verifying that the all the versions are bundled into the library.

**Review by jim-docker — APPROVED** [review]

**Comment by jim-docker** [comment]
Maybe release with just https://github.com/lensapp/lens/pull/7504, which we're pretty confident about, so that we can get the latest pro extensions out ASAP? Then do another release with  https://github.com/lensapp/lens/pull/7515. Do we really need https://github.com/lensapp/lens/pull/7424 now too? What's causing the test failures?

**Comment by jim-docker** [comment]
> That PR is necessary to fix a critical bug where CAs are not being loaded.
> 
> It has been tested by verifying that the all the versions are bundled into the library.

Could we make a beta and get some of the impacted customers to test it?

**Comment by Nokel81** [comment]
We can certainly make a version to test of Lens Desktop before publishing.

**Pull request merged**
