### PR TITLE
FIX: get back to webview  / empty cluster-view bug

### LINKED ISSUE #946: Empty dashboard after removing and re-adding the same cluster
**Describe the bug**
I will see occasionally empty dashboard after removing cluster and re-adding it back 

**To Reproduce**
1. Remove cluster
2. Add the same cluster
3. Repeat steps 1 & 2
4. See empty dashboard

**Expected behavior**
Dashboard should be opened correctly

### PR DESCRIPTION
**Pull request by ixrock**
Switching back to `webview` since `iframe` not reliable and might start missing IPC-events for some reasons.
This could be reproduced by multiple attempts to add/remove same cluster, which might leads to empty cluster-view screen.

### CODE REVIEW

**Comment by nevalla** [comment]
We should the same mechanism for both development and production, so I suggest we will switch completely to WebView. Or any cons on that solution?

**Comment by ixrock** [comment]
@nevalla why? `webview` is just extended, more featured iframe,so if something would work for `iframe` then it definitely should work for `webview`, right?
Switching fully to webview making development process PITA (needs for extra devTools per webview, no quick DOM inspection for whole UI).

**Comment by nevalla** [comment]
> @nevalla why? `webview` is just extended, more featured iframe,so if something would work for `iframe` then it definitely should work for `webview`, right?

I'm just trying to avoid works on `dev` environment kind of issues. Yes it **should** work, but are we really sure it **will**.

**Comment by ixrock** [comment]
@jakolehm wdyt?

**Comment by nevalla** [comment]
Maybe switching to use iframe should be behind some flag instead of `isDevelopment` and `isProduction` ?

**Comment by Nokel81** [comment]
For what it is worth, I think adding a new dev-tools for each cluster to the "Tools" menu shouldn't be too bad a development experience as long as they were named well.

**Comment by jakolehm** [comment]
IMHO we should have the same tag in both environments. 

Btw I cannot reproduce this issue if I first disconnect a cluster before removing it.. so would actual fix be that Lens triggers a disconnect event automatically before removing a cluster?

**Comment by jakolehm** [comment]
I'm not completely happy with the fact that we are again switching back to webview. I could reproduce this issue and after loooong debug session I realised that an iframe cleanup causes IPC to misbehave. Still investigating if it's possible to cleanup an iframe contents without causing IPC problems.

**Comment by ixrock** [comment]
closing in favour #954

**Pull request closed without merging**
