### PR TITLE
poll for pods and services disappearing to remove dead port-forwards

### PR DESCRIPTION
**Pull request by jim-docker**
Signed-off-by: Jim Ehrismann <jehrismann@mirantis.com>

related to #2340

### CODE REVIEW

**Comment by jim-docker** [comment]
Is there a better way than polling?

**Comment by Nokel81** [comment]
> Is there a better way than polling?

You probably could start up a `watch` request. But I wonder if it is really necessary, does the port forwarding not fail if the pod is removed?

**Comment by jim-docker** [comment]
> > Is there a better way than polling?
> 
> You probably could start up a `watch` request. But I wonder if it is really necessary, does the port forwarding not fail if the pod is removed?

When a pod is terminated the `kubectl port-forward` process does not stop, and the port is not released. This happens when run from the command line too. The process does report errors however, like:
```
E1013 11:48:34.876047   37778 portforward.go:400] an error occurred forwarding 40400 -> 3000: error forwarding port 3000 to pod ...
```

**Comment by Nokel81** [comment]
So you could just hook into the pod store watch, right?

**Comment by jim-docker** [comment]
right, thanks

**Comment by jim-docker** [comment]
needs redoing due to port-forward refactoring, plus will try using pod/service watch instead

**Pull request closed without merging**
