### PR TITLE
Extension Api docs should point to generated index files

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

Screenshots of new layout:

Screen Shot 2021-05-28 at 9 04 47 AM
Screen Shot 2021-05-28 at 9 04 53 AM

### CODE REVIEW

**Review by stevejr — APPROVED** [review]
LGTM

**Comment by leenamba** [comment]
Should the title be "Lens Extension Development" instead of API?

**Comment by Nokel81** [comment]
@leenamba Sure, but this PR doesn't touch that.

**Comment by stevejr** [comment]
> Should the title be "Lens Extension Development" instead of API?

@leenamba - If we want the title of the docs changed we can - maybe we can do this in #2896

**Comment by leenamba** [comment]
OK, LGTM

**Review by leenamba — APPROVED** [review]

**Pull request merged**
