### PR TITLE
Add extension uninstall

### PR DESCRIPTION
**Pull request by panuhorsmalahti**
- Add "Uninstall" button to the extensions page
- Implemented on top of #1518, review that first

Things to implement in later PRs:
- Add confirmation dialog before extension is uninstalled
- Disable Uninstall button while uninstall is in progress
- Show notification when extension is uninstalled successfully (I think this would be nice)

Screenshot 2020-11-25 at 16 22 52

### CODE REVIEW

**Comment by Nokel81** [comment]
Will wait to review this until after the lower PR is merged

**Review by chenhunghan — APPROVED** [review]
LGTM!

**Comment by jakolehm** [comment]
@panuhorsmalahti could you resolve conflicts?

**Comment by jakolehm** [comment]
@panuhorsmalahti hitting uninstall does not give any feedback to user ... I think we could show a spinner and disable button while uninstalling.

**Comment by panuhorsmalahti** [comment]
I'm implementing the button disable now. Could it be a separate PR?

**Comment by jakolehm** [comment]
> I'm implementing the button disable now. Could it be a separate PR?

Yes it can be a separate PR. I'll merge this.

**Pull request merged**
