### PR TITLE
Add SystemName validation to AccessibleNamespaces

### LINKED ISSUE #2727: Feature request: Clean input for accesible namespaces
Hi there!

This morning added a new cluster to Lens, but it wasn't showing anything.
I copied the namespace-names from Rancher into lens, but turns out, I accidentally copied it with a space in front: `<space>namespace-name`
Would be nice if characters that can't be in a namespace-name anyway, would be cleaned on input.

Though my colleagues and I are very happy with Lens, thanks!

Kind regards

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2727 

supersedes #2730

### CODE REVIEW

**Review by jim-docker — COMMENTED** [review]
The debounce appears to only work once. If I erase the entry and repeat, I am informed of invalid space or dash immediately, even though I'm typing fast.

**Comment by jim-docker** [comment]
probably not related, but I noticed that if you specify a very long name and submit, the trash icon is missing. How to delete the namespace?

Screen Shot 2021-05-27 at 8 40 31 PM

**Comment by Nokel81** [comment]
Thanks for finding those two issues, will investigate tomorrow.

**Comment by Nokel81** [comment]
@jim-docker I'll fix the horizontal scroll issue in this PR, but the other issue is something that is out of scope of this PR, since it would require changing a lot of `<Input>`.

**Review by jim-docker — APPROVED** [review]
It's fine to check for invalid characters on-the-fly but I'm not a big fan of on-the-fly validation of character combinations (like `-` is ok as long as it's not the first or last character). I think that kind of thing should be checked on submission.

**Comment by Nokel81** [comment]
@jim-docker I agree. Though that requires debouncing the validation or having two different validators (which I think is worse). Something to do in a different PR.

**Pull request merged**
