### PR TITLE
Implement newer add cluster screen

### LINKED ISSUE #2568: Improve Add Cluster UI
**What would you like to be added**:
Switch the selection of context to a list of labelled toggles. In conjunction it should display contexts that are invalid with errors in line (and the toggle itself being disabled).

**Why is this needed**:

Currently, when selecting a kubeconfig the contexts are detected and put into a dropdown. However, this makes for less than ideal UX since it requires 2 addtional clicks (one to open the drop down and one to close it) whenever selecting context(s).

### PR DESCRIPTION
**Pull request by Nokel81**
- Improved UI and code paths leading to cleaner code and better UX for
  misconfigured entries

- Cleanup kube helpers to facilitate clearer FS interactions

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2568 

---

New
---
Screen Shot 2021-04-19 at 4 10 16 PM

### CODE REVIEW

**Comment by Nokel81** [comment]
I have removed the file tab as that is no longer needed due to kubeconfig sync. And I have improved the error reporting so that even with some invalid inputs the user can still proceed. See bellow for newer version.

Screen Shot 2021-04-30 at 5 38 01 PM

**Comment by jakolehm** [comment]
Probably can be closed because we have kubeconfig-sync (and updated "add" screen).

**Comment by Nokel81** [comment]
@jakolehm I disagree because this is the newer add cluster screen for C&P

**Comment by jakolehm** [comment]
> @jakolehm I disagree because this is the newer add cluster screen for C&P

Why do we have "select kubeconfig file" here... I thought we should not have that anymore (because of kubeconfig sync)?

**Comment by Nokel81** [comment]
@jakolehm https://github.com/lensapp/lens/pull/2570#issuecomment-830415131 has the more up to date image

**Comment by jakolehm** [comment]
> @jakolehm [#2570 (comment)](https://github.com/lensapp/lens/pull/2570#issuecomment-830415131) has the more up to date image

Ok, but I already removed (on purpose) the context selector. Now that we have the catalog & sync it does not really make sense to hand-pick contexts from a _pasted_ kubeconfig.

**Comment by Nokel81** [comment]
Closing as scope has now changed. Will open a new PR with new scope.

**Pull request closed without merging**
