### PR TITLE
Release v4.1.3

### PR DESCRIPTION
**Pull request by jakolehm**
## 🐛 Bug Fixes

* Fix loading all namespaces for users with limited cluster access (#2217) @nevalla
* StatusBarRegistration's component field must be optional for backwards compatability (#2211) @Nokel81
* Fix: deprecated helm chart filtering (#2158) @aleksfront
* Display environment variables coming from secret in pod details (#2167) @nevalla
* Fix RoleBindingDetails not rendering the name of the role binding (#2204) @Nokel81
* Fix Documentation: Using Helm Charts (#2202) @stevenGravy
* Fix auto update on quit with newer version (#2128) @Nokel81
* Fix: allow scrolling in main-layout's content area (#2201) @ixrock
* fix RoleBindings Namespace and Bindings field not displaying the correct data (#2203) @Nokel81
* Fix: don't reset selected namespaces to defaults in case of "All namespaces" on page reload (#2185) @ixrock
* Fix Documentation: fix broken link in getting-started page (#2155) @rafedramzi

### CODE REVIEW

**Review by Nokel81 — APPROVED** [review]

**Review by aleksfront — APPROVED** [review]

**Comment by jim-docker** [comment]
don't know if this is a showstopper (namespace selector field is double high), not quite sure how I made it happen:


https://user-images.githubusercontent.com/40840436/109027411-c061ca80-768e-11eb-8cd6-70b23cdc9298.mov

It is stuck that way until you reload the view or restart the app.

**Comment by jakolehm** [comment]
> don't know if this is a showstopper (namespace selector field is double high), not quite sure how I made it happen:
> 

@jim-docker probably caused by an extension (I don't see that behaviour on my local build)?

**Comment by jim-docker** [comment]
Helm repo UI is busted?


https://user-images.githubusercontent.com/40840436/109031958-37995d80-7693-11eb-9851-ddd36652a3cd.mov

**Comment by jim-docker** [comment]
> Helm repo UI is busted?
> 

Though it's not a regression, I can reproduce in 4.1.2...

**Comment by jim-docker** [comment]
> > Helm repo UI is busted?
> 
> Though it's not a regression, I can reproduce in 4.1.2...

It looks like it is again related to lens-extension-cc

**Review by jim-docker — APPROVED** [review]

**Comment by Nokel81** [comment]
> > > Helm repo UI is busted?
> > 
> > 
> > Though it's not a regression, I can reproduce in 4.1.2...
> 
> It looks like it is again related to lens-extension-cc

Oh is that extension messing with the css or are we not rendering the components correctly?

**Pull request merged**
