### PR TITLE
Get `npm run dev` to work again

### PR DESCRIPTION
**Pull request by Nokel81**
Current state:
1. In one terminal run `npm run dev:library` at the root 
2. In a second terminal (once the first terminal goes to watch mode) run `npm run dev-run` in `packages/open-lens`

Problems:
1. ~The rebuild order seems to be wrong, namely if `@k8slens/core` changes then it rebuilds all of the dependencies of `@k8slens/core` and then rebuilds `@k8slens/core` instead of rebuilding `@k8slens/core` and then all of its dependents.~
2. The next problem is that now only the package that changes is rebuilt, but none of its dependents are after it is finished.

### CODE REVIEW

**Comment by gabriel-mirantis** [comment]
`npm run before-dev-actions` before `npm run dev:library` on the root followed by `npm run dev-run` in `packages/open-lens` is working

**Comment by jansav** [comment]
It would make more sense to me if we:

1. Remove all `dev` scripts from the packages
2. Introduce `start` script to packages which want to start something (e.g. open-lens) 
3. Introduce **one** `dev` script in the root package.json which uses `lerna watch` to run `npm run build` in packages. 
4. Introduce **one** `start` script in the root package.json which the stuff that needs to be started (e.g. applications)

In that way, we would utilize `lerna` / `nx` to figure out what are the packages that changed, and then it would benefit of knowing package dependencies and therefore rebuild changed packages and the packages that are using the changed package. 

Something like this is operating in one of the repositories (monorepo) in the organization. Keep in mind, that the `npm run build` script will need a flag for development and to do so with minimal duplication, I think we should introduce our own script in the `@k8slens/webpack` package

**Comment by jansav** [comment]
Another topic is the `pre-*` and `post-*` scripts, which are sign of trouble to me. It shouldn't be that hard to make the scripts not entangled (coupled) with each other.

**Comment by Nokel81** [comment]
@jansav let me try that

**Comment by Nokel81** [comment]
> In that way, we would utilize lerna / nx to figure out what are the packages that changed, and then it would benefit of knowing package dependencies and therefore rebuild changed packages and the packages that are using the changed package.

NOTE: we are currently doing that in this PR

**Pull request closed without merging**
